using System.Diagnostics;
using System.Globalization;
using System.Text.RegularExpressions;
namespace KeyboardScreen.Core;
public sealed class WindowsSystemSnapshotSource:ISystemSnapshotSource{
public async ValueTask<SystemSnapshot> ReadAsync(CancellationToken cancellationToken=default){double cpu=0,memory=0;try{string top=await RunAsync("top","-l 1 -n 0",cancellationToken);var m=Regex.Match(top,@"CPU usage:\s*([\d.]+)% user,\s*([\d.]+)% sys");if(m.Success)cpu=Parse(m.Groups[1].Value)+Parse(m.Groups[2].Value);string vm=await RunAsync("vm_stat","",cancellationToken);string size=await RunAsync("sysctl","-n hw.memsize",cancellationToken);double total=double.Parse(size.Trim(),CultureInfo.InvariantCulture);double free=0;foreach(Match line in Regex.Matches(vm,@"Pages (free|inactive|speculative):\s*(\d+)\."))free+=double.Parse(line.Groups[2].Value,CultureInfo.InvariantCulture)*4096;memory=Math.Clamp((total-free)/total*100,0,100);}catch{}return new SystemSnapshot(DateTimeOffset.Now,cpu,memory);}
private static double Parse(string v)=>double.Parse(v,CultureInfo.InvariantCulture);internal static async Task<string> RunAsync(string file,string args,CancellationToken ct){var psi=new ProcessStartInfo(file,args){RedirectStandardOutput=true,RedirectStandardError=true,UseShellExecute=false,CreateNoWindow=true};using var p=Process.Start(psi)??throw new InvalidOperationException();string output=await p.StandardOutput.ReadToEndAsync(ct);await p.WaitForExitAsync(ct);return output;}}
public sealed class WindowsMusicSnapshotSource:IMusicSnapshotSource{
public bool IgnoreBrowserSessions { get; set; } = true;
public async ValueTask<MusicSnapshot> ReadAsync(CancellationToken cancellationToken=default){foreach(string app in new[]{"Music","Spotify"}){try{string script=$"tell application \"System Events\" to set runningNow to exists process \"{app}\"\nif runningNow then\n tell application \"{app}\"\n  set t to name of current track\n  set a to artist of current track\n  set d to duration of current track\n  set p to player position\n  set s to player state as string\n  return t & \"|||\" & a & \"|||\" & d & \"|||\" & p & \"|||\" & s\n end tell\nend if";string result=await WindowsSystemSnapshotSource.RunAsync("osascript","-e "+Quote(script),cancellationToken);var parts=result.Trim().Split("|||",StringSplitOptions.None);if(parts.Length>=5)return new MusicSnapshot(true,parts[0],parts[1],TimeSpan.FromSeconds(Parse(parts[3])),TimeSpan.FromSeconds(Parse(parts[2])),parts[4].Contains("playing",StringComparison.OrdinalIgnoreCase),null);}catch{}}return MusicSnapshot.Unavailable;}
private static string Quote(string s)=>"\""+s.Replace("\\","\\\\").Replace("\"","\\\"").Replace("\n","\\n")+"\"";private static double Parse(string v)=>double.TryParse(v,NumberStyles.Float,CultureInfo.InvariantCulture,out var x)?x:0;}