using SkiaSharp;
namespace KeyboardScreen.Core;
public sealed class ScreenCanvas{
private readonly SKCanvas _canvas;public ScreenProfile Profile{get;}public Color AccentColor{get;}public FontFamily FontFamily{get;}public ScreenDisplayOptions DisplayOptions{get;}public Rect SafeBounds=>new(Profile.SafeArea.Left,Profile.SafeArea.Top,Profile.Width-Profile.SafeArea.Left-Profile.SafeArea.Right,Profile.Height-Profile.SafeArea.Top-Profile.SafeArea.Bottom);
internal ScreenCanvas(SKCanvas canvas,ScreenProfile profile,Color accent,FontFamily font,ScreenDisplayOptions options){_canvas=canvas;Profile=profile;AccentColor=accent;FontFamily=font;DisplayOptions=options;}
public void Fill(Color c)=>_canvas.Clear(c.Skia);
public void Gradient(Color a,Color b,Point p1,Point p2){using var paint=new SKPaint{Shader=SKShader.CreateLinearGradient(new((float)(p1.X*Profile.Width),(float)(p1.Y*Profile.Height)),new((float)(p2.X*Profile.Width),(float)(p2.Y*Profile.Height)),new SKColor[]{a.Skia,b.Skia},null,SKShaderTileMode.Clamp)};_canvas.DrawRect(0,0,Profile.Width,Profile.Height,paint);}
public void RoundedRect(Rect r,double radius,Color fill,Color? stroke=null,double strokeWidth=1){using var p=Paint(fill,SKPaintStyle.Fill);_canvas.DrawRoundRect(ToSk(r),(float)radius,(float)radius,p);if(stroke is{}s){using var o=Paint(s,SKPaintStyle.Stroke,strokeWidth);_canvas.DrawRoundRect(ToSk(r),(float)radius,(float)radius,o);}}
public void Ellipse(Rect r,Color fill,Color? stroke=null,double strokeWidth=1){using var p=Paint(fill,SKPaintStyle.Fill);_canvas.DrawOval(ToSk(r),p);if(stroke is{}s){using var o=Paint(s,SKPaintStyle.Stroke,strokeWidth);_canvas.DrawOval(ToSk(r),o);}}
/// <summary>Draws at <paramref name="origin"/>. Right and centre alignment place the text inside a box <paramref name="maxWidth"/> wide; without a width there is no box, so they align against the origin itself - the text ends at it, or is centred on it.</summary>
public void Text(string value,double size,Color color,Point origin,FontWeight? weight=null,TextAlignment alignment=TextAlignment.Left,double maxWidth=double.PositiveInfinity,double maxHeight=double.PositiveInfinity){using var font=CreateFont(value,size,weight??FontWeights.Normal,FontFamily);using var paint=Paint(color,SKPaintStyle.Fill);var text=Fit(value,font,maxWidth);var width=font.MeasureText(text,paint);var box=double.IsPositiveInfinity(maxWidth)?0:maxWidth;var x=(float)origin.X+(alignment switch{TextAlignment.Center=>(float)((box-width)/2),TextAlignment.Right=>(float)(box-width),_=>0});_canvas.DrawText(text,x,(float)origin.Y-font.Metrics.Ascent,font,paint);}
public void CenteredText(string value,double size,Color color,Rect bounds,FontWeight? weight=null)=>AlignedText(value,size,color,bounds,weight,TextAlignment.Center);
public void AlignedText(string value,double size,Color color,Rect bounds,FontWeight? weight=null,TextAlignment alignment=TextAlignment.Left,FontFamily? fontFamily=null){using var font=CreateFont(value,size,weight??FontWeights.Normal,fontFamily??FontFamily);using var paint=Paint(color,SKPaintStyle.Fill);var text=Fit(value,font,bounds.Width);var width=font.MeasureText(text,paint);var m=font.Metrics;var x=alignment switch{TextAlignment.Right=>(float)(bounds.Right-width),TextAlignment.Center=>(float)(bounds.Left+(bounds.Width-width)/2),_=>(float)bounds.Left};var baseline=(float)(bounds.Top+(bounds.Height-(m.Descent-m.Ascent))/2)-m.Ascent;_canvas.DrawText(text,x,baseline,font,paint);}
public void Line(Point a,Point b,Color c,double thickness=1){using var p=Paint(c,SKPaintStyle.Stroke,thickness);p.StrokeCap=SKStrokeCap.Round;_canvas.DrawLine((float)a.X,(float)a.Y,(float)b.X,(float)b.Y,p);}
public void Path(Geometry g,Color stroke,double thickness=1,Color? fill=null){if(fill is{}f){using var fp=Paint(f,SKPaintStyle.Fill);_canvas.DrawPath(g.Path,fp);}using var sp=Paint(stroke,SKPaintStyle.Stroke,thickness);sp.StrokeCap=SKStrokeCap.Round;sp.StrokeJoin=SKStrokeJoin.Round;_canvas.DrawPath(g.Path,sp);}
public void ProgressBar(Rect r,double percent,Color track,Color fill){RoundedRect(r,r.Height/2,track);var w=Math.Max(r.Height,r.Width*Math.Clamp(percent,0,100)/100);RoundedRect(new(r.X,r.Y,w,r.Height),r.Height/2,fill);}
public void Image(byte[] bytes,Rect rect,double radius=0){using var bitmap=SKBitmap.Decode(bytes);if(bitmap is null)return;var scale=Math.Max((float)rect.Width/bitmap.Width,(float)rect.Height/bitmap.Height);var w=bitmap.Width*scale;var h=bitmap.Height*scale;var dest=new SKRect((float)(rect.Left+(rect.Width-w)/2),(float)(rect.Top+(rect.Height-h)/2),(float)(rect.Left+(rect.Width+w)/2),(float)(rect.Top+(rect.Height+h)/2));_canvas.Save();_canvas.ClipRoundRect(new SKRoundRect(ToSk(rect),(float)radius));using var p=new SKPaint{IsAntialias=true};_canvas.DrawBitmap(bitmap,dest,p);_canvas.Restore();}
private static SKPaint Paint(Color c,SKPaintStyle style,double width=1)=>new(){Color=c.Skia,Style=style,StrokeWidth=(float)width,IsAntialias=true};private static SKRect ToSk(Rect r)=>new((float)r.Left,(float)r.Top,(float)r.Right,(float)r.Bottom);
private static string Fit(string value,SKFont font,double max){if(double.IsPositiveInfinity(max)||font.MeasureText(value)<=max)return value;const string e="…";var n=value.Length;while(n>0&&font.MeasureText(value[..n]+e)>max)n--;return n==0?string.Empty:value[..n]+e;}
private static SKFont CreateFont(string text,double size,FontWeight weight,FontFamily family){SKTypeface? face=family.FilePath is{Length:>0}&&File.Exists(family.FilePath)?SKTypeface.FromFile(family.FilePath):SKTypeface.FromFamilyName(family.Name,new SKFontStyle(weight.Value,5,SKFontStyleSlant.Upright));var cp=text.EnumerateRunes().Select(r=>r.Value).FirstOrDefault(v=>v>127);if(cp>0&&(face is null||!face.ContainsGlyph(cp))){face?.Dispose();face=SKFontManager.Default.MatchCharacter(family.Name,weight.Value,5,SKFontStyleSlant.Upright,null,cp);}return new SKFont(face??SKTypeface.Default,(float)size){Edging=SKFontEdging.Antialias,Subpixel=true};}}