# -*- coding: utf-8 -*-
# Desktop UI strings. zh keeps the project's original wording verbatim.
UI = [
    # ---- language picker ------------------------------------------------------
    ("LanguageHeading", "Language", "Мова", "语言"),

    # ---- shared ---------------------------------------------------------------
    ("CommonCancel", "Cancel", "Скасувати", "取消"),

    # ---- accent color window --------------------------------------------------
    ("AccentTitle", "Choose accent color", "Оберіть акцентний колір", "选择主题强调色"),
    ("AccentHint", "Drag the color field and the hue bar to pick a color", "Перетягніть поле кольору та смугу відтінку", "拖动色域与色相条选择颜色"),
    ("AccentApply", "Apply color", "Застосувати колір", "应用颜色"),

    # ---- tray menu ------------------------------------------------------------
    ("TrayShowWindow", "Open main window", "Відкрити головне вікно", "打开主窗口"),
    ("TrayExit", "Exit", "Вийти", "退出"),

    # ---- first-run guide ------------------------------------------------------
    ("GuideTitle", "Connect your Linx68", "Підключіть свій Linx68", "连接你的 Linx68"),
    ("GuideSubtitle", "Turn on the keyboard's Image API in four steps", "Увімкніть Image API клавіатури за чотири кроки", "开启键盘图像 API，只需完成下面四步"),
    ("GuideStep1", "Put the keyboard on the same network as this PC", "Підключіть клавіатуру до тієї ж мережі, що й комп'ютер", "确保键盘连接到和电脑相同的局域网"),
    ("GuideStep2", "Click the knob to open the menu", "Натисніть на ручку, щоб відкрити меню", "单击旋钮进入菜单"),
    ("GuideStep3", "Turn the knob to Image API", "Прокрутіть до Image API", "旋转选择图像 API"),
    ("GuideStep4", "Scan the code to get the IP address", "Скануйте код, щоб отримати IP-адресу", "扫码获取 IP 地址"),
    ("GuideDeviceIp", "Device IP address", "IP-адреса пристрою", "设备 IP 地址"),
    ("GuideLater", "Set up later", "Пізніше", "稍后设置"),
    ("GuideSaveContinue", "Save and continue", "Зберегти й продовжити", "保存并继续"),

    # ---- main window chrome ---------------------------------------------------
    ("TitleBarThemeToggle", "Switch light / dark mode", "Перемкнути світлу / темну тему", "切换亮色 / 暗色模式"),
    ("AppHeading", "Keyboard display", "Екран клавіатури", "键盘显示屏"),
    ("SidebarThemesHeading", "Screen themes", "Теми екрана", "显示方案"),
    ("DeviceAddress", "Device address", "Адреса пристрою", "设备地址"),
    ("NavScreen", "Screen setup", "Налаштування екрана", "屏幕配置"),
    ("NavTheme", "Theme settings", "Налаштування теми", "主题设置"),
    ("NavAutomation", "Automation", "Автоматизація", "自动化"),
    ("NavSettings", "Other settings", "Інші налаштування", "其他设置"),
    ("NavAbout", "About", "Про програму", "关于"),

    # ---- screen page ----------------------------------------------------------
    ("ScreenCurrentTheme", "Current theme", "Поточна тема", "当前显示方案"),
    ("ScreenContentHeading", "What's on screen", "Вміст екрана", "画面内容"),
    ("ScreenCurrentData", "Current data", "Поточні дані", "当前数据"),
    ("ScreenChooseImage", "Choose image", "Обрати зображення", "选择图片"),
    ("ScreenFontHeading", "Screen font", "Шрифт екрана", "屏幕字体"),
    ("ScreenOpenFontsFolder", "Open fonts folder", "Відкрити теку шрифтів", "打开字体文件夹"),
    ("ScreenAccentHeading", "Accent color", "Акцентний колір", "主题强调色"),
    ("ScreenChooseColor", "Choose color", "Обрати колір", "选择颜色"),
    ("ImageTimePlacementHeading", "Clock position", "Розташування годинника", "图片时间位置"),
    ("ProgressPeriodHeading", "Progress period", "Період прогресу", "进度周期"),
    ("TopInfoHeading", "Header", "Верхній рядок", "顶部信息"),
    ("FontSizeLabel", "Type size", "Кегль", "字号"),
    ("ImageClockHeading", "Image clock", "Годинник на фото", "图片时钟"),
    ("ClockStyleLabel", "Clock style", "Стиль годинника", "时钟样式"),
    ("TextColorLabel", "Text color", "Колір тексту", "文字颜色"),
    ("TextAlignmentLabel", "Alignment", "Вирівнювання", "信息对齐"),
    ("TimeBackgroundLabel", "Time backdrop", "Підкладка часу", "时间背景"),
    ("ShowWeatherLabel", "Show weather", "Показувати погоду", "显示天气"),
    ("DigitalLayoutHeading", "Digital clock layout", "Компонування цифрового годинника", "数字时钟排版"),
    ("ContentOrderLabel", "Order", "Порядок", "内容顺序"),
    ("TimeSizeLabel", "Time size", "Кегль часу", "时间字号"),
    ("DateSizeLabel", "Date size", "Кегль дати", "日期字号"),
    ("WeatherSizeLabel", "Weather size", "Кегль погоди", "天气字号"),
    ("LargeDigitalLayoutHeading", "Large digital layout", "Компонування великих цифр", "大数字时间排版"),
    ("AnalogLayoutHeading", "Analog clock layout", "Компонування стрілкового годинника", "模拟时钟排版"),
    ("ClockSizeLabel", "Clock size", "Розмір годинника", "时钟大小"),
    ("FlipLayoutHeading", "Flip clock layout", "Компонування перекидного годинника", "翻页时钟排版"),
    ("WeatherHeading", "Weather", "Погода", "天气"),
    ("WeatherAutoLocationHint", "Auto-location shows the city it detects.", "Автовизначення покаже знайдене місто.", "自动定位会显示当前识别到的城市。"),
    ("WeatherAutoLocation", "Auto-locate", "Автовизначення", "自动定位"),
    ("WeatherCityLabel", "City", "Місто", "城市"),
    ("PerfVisualHeading", "Performance graph modules", "Модулі графіків продуктивності", "性能可视化模块"),
    ("PerfVisualHint", "Modules you turn off leave the screen; the rest rearrange automatically.", "Вимкнені модулі зникають з екрана, решта перекомпоновується автоматично.", "关闭的模块会从画面中移除，其余模块自动重新排列。"),
    ("LabelMemory", "Memory", "Пам'ять", "内存"),
    ("LabelDownload", "Download", "Завантаження", "下载"),
    ("LabelUpload", "Upload", "Вивантаження", "上传"),

    # ---- stocks ---------------------------------------------------------------
    ("StocksHint",
     "Add up to five, each with its own show/hide switch (keep at least two). Supports A-shares (600519.SS), Hong Kong (0700.HK) and US (AAPL) on Tencent/Yahoo, and crypto pairs (BTCUSDT) on the Binance source; BTC-USD also works via Yahoo. With exactly two enabled you get a five-day trend comparison. Data may be delayed or inaccurate and is not investment advice.",
     "Можна додати до п'яти, кожен зі своїм перемикачем показу (щонайменше два). Підтримуються A-акції (600519.SS), Гонконг (0700.HK) і США (AAPL) через Tencent/Yahoo, а крипто-пари (BTCUSDT) — через джерело Binance; BTC-USD також працює через Yahoo. Якщо увімкнено рівно два, показується порівняння за 5 днів. Дані можуть бути із затримкою або неточними й не є інвестиційною порадою.",
     "最多添加五项，每项可单独开关显示（最少保留两只）。腾讯/雅虎源支持 A股（600519.SS）、港股（0700.HK）、美股（AAPL)；币安源支持加密货币交易对（BTCUSDT），BTC-USD 也可经雅虎源使用。恰好启用两只时显示 5 日走势对比。数据可能延迟或不准确，不构成投资建议。"),
    ("StocksSymbolLabel", "Symbol", "Код", "行情代码"),
    ("StocksAliasLabel", "Display alias (optional)", "Псевдонім (необов'язково)", "显示别名（可选）"),
    ("StocksShowLabel", "Show", "Показ", "显示"),
    ("StocksAliasPlaceholder2", "Tencent", "Tencent", "腾讯"),
    ("StocksAliasPlaceholder4", "Moutai", "Moutai", "贵州茅台"),
    ("StocksAliasPlaceholder5", "Ping An Bank", "Ping An Bank", "平安银行"),
    ("StocksColorLabel", "Gain/loss colors", "Кольори зростання/падіння", "涨跌颜色"),
    ("StocksCacheNote", "15-minute cache · display only", "Кеш 15 хв · лише для показу", "15 分钟缓存 · 行情仅供展示"),
    ("StocksSourceLabel", "Data source", "Джерело даних", "行情数据源"),
    ("StocksSourceHint", "Tencent works inside mainland China, Yahoo needs international access, Binance covers crypto pairs.", "Tencent працює в материковому Китаї, Yahoo потребує міжнародного доступу, Binance — для крипто-пар.", "腾讯国内直连；雅虎需外网；币安用于加密货币交易对"),
    ("StockColorRedUp", "Red up / green down", "Червоний — вгору, зелений — вниз", "红涨绿跌"),
    ("StockColorGreenUp", "Green up / red down", "Зелений — вгору, червоний — вниз", "绿涨红跌"),
    ("StockSourceTencent", "Tencent", "Tencent", "腾讯行情"),
    ("StockSourceYahoo", "Yahoo Finance", "Yahoo Finance", "雅虎 Finance"),

    # ---- Tokscale / AI usage --------------------------------------------------
    ("TokscaleHeading", "Tokscale data source", "Джерело даних Tokscale", "Tokscale 数据源"),
    ("TokscaleInstallDocs", "Install guide", "Інструкція", "安装说明"),
    ("TokscaleRecheck", "Check again", "Перевірити знову", "重新检测"),
    ("TokscaleLocalOnly", "Local data only", "Лише локальні дані", "只读取本机数据"),
    ("TokscaleLocalOnlyHint",
     "KSS only calls Tokscale's JSON commands on this machine. It does not take over account sign-in, does not read API keys, and never uploads usage or credentials.",
     "KSS лише викликає JSON-команди Tokscale на цьому комп'ютері. Він не керує входом в акаунти, не читає API-ключі й нікуди не надсилає дані про використання чи облікові дані.",
     "KSS 仅调用本机 Tokscale 的 JSON 命令，不接管账号登录、不读取 API Key，也不会上传用量或凭据。"),
    ("TokscaleThreeSteps", "First time? Three steps.", "Перший запуск? Три кроки.", "首次使用，只需完成下面三步"),
    ("TokscaleStep1", "Install Node.js and Tokscale", "Встановіть Node.js і Tokscale", "安装 Node.js 与 Tokscale"),
    ("TokscaleStep1Hint", "Run in a terminal: npm install -g tokscale@latest", "Виконайте в терміналі: npm install -g tokscale@latest", "在终端执行：npm install -g tokscale@latest"),
    ("TokscaleStep2", "Let Tokscale scan this machine", "Дайте Tokscale просканувати комп'ютер", "让 Tokscale 扫描本机记录"),
    ("TokscaleStep2Hint", "After installing, run tokscale once in a terminal", "Після встановлення один раз запустіть tokscale у терміналі", "安装后在终端运行一次 tokscale"),
    ("TokscaleStep3", "Come back to KSS and check again", "Поверніться в KSS і перевірте знову", "回到 KSS 重新检测"),
    ("TokscaleStep3Hint", "Once detected you can pick subscription quota, model tokens or cost.", "Після виявлення можна обрати ліміт підписки, токени моделі або вартість.", "检测成功后即可选择订阅额度、模型 Token 或费用。"),
    ("AiMetricLabel", "Metric", "Показник", "显示指标"),
    ("AiDataItemLabel", "Data item", "Елемент даних", "数据项目"),
    ("AiDataItemHint", "The list comes from what Tokscale actually reports right now", "Список формується з того, що Tokscale зараз реально повертає", "下拉项来自 Tokscale 当前实际读取到的数据"),
    ("AiDisplayNameLabel", "Name on screen (optional)", "Назва на екрані (необов'язково)", "屏幕显示名称（可选）"),
    ("AiDisplayNamePlaceholder", "Leave empty to use the platform or model name", "Порожньо — буде назва платформи або моделі", "留空则使用平台或模型名称"),
    ("AiGoalLabel", "Progress target (optional)", "Ціль прогресу (необов'язково)", "进度目标（可选）"),
    ("AiGoalHint", "Leave it empty or 0 to show the real figure without inventing a percentage", "Порожньо або 0 — показує реальне значення без вигаданих відсотків", "留空或填 0 时只显示真实数值，不虚构百分比"),
    ("AiKindSubscription", "Subscription quota left", "Залишок за підпискою", "订阅剩余额度"),
    ("AiKindSubscriptionHint", "Reads the period quota and reset time from Tokscale Usage", "Читає ліміт періоду й час скидання з Tokscale Usage", "读取 Tokscale Usage 中的周期额度与重置时间"),
    ("AiKindModelTokens", "Model tokens", "Токени моделі", "模型 Token"),
    ("AiKindModelTokensHint", "Cumulative tokens by client, provider and model", "Сумарні токени за клієнтом, провайдером і моделлю", "按客户端、供应商和模型显示累计 Token"),
    ("AiKindModelCost", "Model cost", "Вартість моделі", "模型费用"),
    ("AiKindModelCostHint", "Estimated cost by client, provider and model", "Оцінена вартість за клієнтом, провайдером і моделлю", "按客户端、供应商和模型显示估算费用"),
    ("TokscaleDetecting", "Detecting Tokscale", "Пошук Tokscale", "正在检测 Tokscale"),
    ("TokscaleReadingLocal", "Reading local usage data…", "Читаю локальні дані використання…", "正在读取本机用量数据…"),
    ("TokscaleStatusReady", "Tokscale connected", "Tokscale підключено", "Tokscale 已连接"),
    ("TokscaleStatusNotInstalled", "Tokscale not detected", "Tokscale не виявлено", "尚未检测到 Tokscale"),
    ("TokscaleStatusNoData", "Tokscale has no data yet", "У Tokscale поки немає даних", "Tokscale 暂无数据"),
    ("TokscaleStatusError", "Tokscale read failed", "Не вдалося прочитати Tokscale", "Tokscale 读取失败"),
    ("TokscaleNoSubscriptionData", "Tokscale is connected, but there is no subscription quota data. Switch to model tokens or model cost.", "Tokscale підключено, але даних про ліміт підписки немає. Перемкніться на токени або вартість моделі.", "Tokscale 已连接，但没有订阅额度数据。可切换到模型 Token 或模型费用。"),
    ("TokscaleNoModelData", "Tokscale is connected, but there are no model statistics right now.", "Tokscale підключено, але зараз немає статистики за моделями.", "Tokscale 已连接，但当前没有模型统计数据。"),

    # ---- automation page ------------------------------------------------------
    ("RefreshHeading", "Scheduled refresh and push", "Періодичне оновлення та надсилання", "定时刷新与推送"),
    ("RefreshHint", "Anything from 1 second to 1 hour. Changes save and push immediately.", "Від 1 секунди до 1 години. Зміни зберігаються й надсилаються одразу.", "1 秒 – 1 小时，可自由输入，设置变更立即保存并推送。"),
    ("AutoPushToggle", "Scheduled push", "Періодичне надсилання", "定时推送"),
    ("MediaSwitchHeading", "Automatic media theme", "Автоперемикання медіатеми", "媒体主题自动切换"),
    ("MediaSwitchHint", "Switch to a chosen theme when playback starts and when it stops.", "Перемикатися на обрану тему на початку й у кінці відтворення.", "播放与停止时分别切换到指定主题。"),
    ("MediaIdleLabel", "When nothing plays", "Коли нічого не грає", "无媒体播放时"),
    ("MediaPlayingLabel", "When playback starts", "Коли почалося відтворення", "检测到播放时"),
    ("IgnoreBrowserMedia", "Ignore browser media", "Ігнорувати медіа з браузера", "忽略浏览器媒体"),
    ("IgnoreBrowserMediaHint", "Do not treat streams or page audio in Chrome, Edge and the like as the current media.", "Не вважати трансляції чи звук зі сторінок у Chrome, Edge тощо поточним медіа.", "不将 Chrome、Edge 等浏览器中的直播或网页音频识别为当前媒体。"),
    ("AutoSwitchMusicHeading", "Switch automatically when music plays", "Автоперемикання під час музики", "播放音乐时自动切换"),
    ("AutoSwitchMusicHint", "Only shown while a music theme is selected.", "Показується лише коли обрано музичну тему.", "仅在当前为音乐类主题时显示。"),

    # ---- settings page --------------------------------------------------------
    ("AppearanceHeading", "Appearance", "Вигляд", "界面外观"),
    ("SafeAreaHeading", "Content safe area", "Безпечна зона вмісту", "内容安全区"),
    ("InsetLeft", "Left", "Ліво", "左"),
    ("InsetTop", "Top", "Верх", "上"),
    ("InsetRight", "Right", "Право", "右"),
    ("InsetBottom", "Bottom", "Низ", "下"),
    ("MinimizeToTray", "Minimize to tray", "Згортати в трей", "最小化到系统托盘"),
    ("CloseToTray", "Close to tray", "Закриття згортає в трей", "关闭后最小化"),
    ("LaunchAtStartup", "Launch at startup", "Запускати при старті системи", "开机自启动"),
    ("StartMinimized", "Start minimized", "Запускати згорнутим", "启动后保持最小化"),

    # ---- about page -----------------------------------------------------------
    ("AboutVersion", "Version {0}", "Версія {0}", "版本 {0}"),
    ("AboutCheckUpdates", "Check for updates", "Перевірити оновлення", "检查更新"),
    ("AboutOpenDownload", "Go to download", "Перейти до завантаження", "前往下载"),
    ("AboutLicenseNote",
     "Keyboard Screen Studio's source code is MIT-licensed. Third-party components, fonts and data services keep their own terms; the app and tray icons are covered by a separate visual-asset license. The full text ships with the program.",
     "Вихідний код Keyboard Screen Studio — під ліцензією MIT. Сторонні компоненти, шрифти й сервіси даних лишаються на власних умовах; іконки програми та трея мають окрему ліцензію на візуальні матеріали. Повний текст постачається разом із програмою.",
     "Keyboard Screen Studio 源代码采用 MIT License。第三方组件、字体与数据服务仍遵循各自条款；应用图标与托盘图标采用单独的视觉资产许可。完整说明随程序提供。"),
    ("AboutFontNote",
     "The default font is MiSans, copyright Xiaomi Inc., used under the MiSans Font Intellectual Property License Agreement.",
     "Типовий шрифт — MiSans, © Xiaomi Inc., використовується за угодою MiSans Font Intellectual Property License Agreement.",
     "默认字体使用 MiSans，版权归小米科技有限责任公司所有，依据《MiSans 字体知识产权许可协议》使用。"),
    ("AboutOpenSourceHeading", "Open-source components", "Компоненти з відкритим кодом", "开源组件"),
    ("AboutMiSansLicense", "MiSans license", "Ліцензія MiSans", "MiSans 许可协议"),
    ("AboutXiaomiCopyright", "Copyright © Xiaomi Inc.", "Copyright © Xiaomi Inc.", "Copyright © 小米科技有限责任公司"),
    ("AboutDataSourcesHeading", "Data sources and disclaimer", "Джерела даних і застереження", "数据来源与声明"),
    ("AboutDataSourcesNote",
     "Weather data comes from Open-Meteo; auto-detected city names are resolved by BigDataCloud. The Tencent/Yahoo quote feeds and Tokscale local usage are unofficial, experimental integrations that may be delayed, inaccurate or stop working; stock information is not investment advice. Keyboard Screen Studio is an independent personal project with no affiliation with, authorization from, endorsement by or sponsorship from the Linx68 device manufacturer or any of the platforms above. The app and tray icons are original AI-assisted visual assets — see ASSET_LICENSE.md.",
     "Дані про погоду надає Open-Meteo, назви автоматично визначених міст — BigDataCloud. Котирування Tencent/Yahoo і локальні дані Tokscale — неофіційні експериментальні інтеграції, які можуть запізнюватися, бути неточними або перестати працювати; інформація про акції не є інвестиційною порадою. Keyboard Screen Studio — незалежний особистий проєкт, не пов'язаний із виробником пристрою Linx68 чи згаданими платформами й не має від них дозволу, схвалення чи спонсорства. Іконки програми та трея — оригінальні візуальні матеріали, створені за допомогою AI; див. ASSET_LICENSE.md.",
     "天气数据由 Open-Meteo 提供，自动定位城市名由 BigDataCloud 解析。腾讯/雅虎行情与 Tokscale 本地用量均为非官方实验性集成，可能延迟、不准确或失效；股票信息不构成投资建议。Keyboard Screen Studio 是独立个人项目，与 Linx68 设备制造商及上述平台不存在隶属、授权、认可或赞助关系。应用与托盘图标为 AI 辅助创作的原创视觉资产，详见 ASSET_LICENSE.md。"),
    ("PreviewHeading", "Preview", "Перегляд", "预览"),

    # ---- risk notice window ---------------------------------------------------
    ("RiskNoticeTitle", "Before you start", "Перш ніж почати", "使用提示"),
    ("RiskNoticeFooter", "You can carry on; this notice appears only once.", "Можете продовжувати; це повідомлення показується лише раз.", "你可以继续使用；此提示只会显示一次。"),
    ("RiskNoticeAck", "Got it", "Зрозуміло", "我已了解"),
    ("RiskStocksTitle", "Stock quotes: a caution", "Котирування акцій: застереження", "股票行情风险提示"),
    ("RiskStocksHeading", "Experimental data feature", "Експериментальна функція даних", "实验性数据功能"),
    ("RiskStocksBody",
     "Stock, fund and digital-asset quotes come from third-party public endpoints and may be delayed, inaccurate, interrupted, or mapped to the wrong symbol. What you see is for on-screen display only and is not investment advice or a basis for trading.",
     "Котирування акцій, фондів і цифрових активів надходять зі сторонніх публічних інтерфейсів і можуть бути із затримкою, неточними, перерваними або зіставленими з хибним кодом. Показана інформація призначена лише для відображення на екрані й не є інвестиційною порадою чи підставою для торгівлі.",
     "股票、基金与数字资产行情来自第三方公开接口，可能存在延迟、不准确、中断或代码映射错误。所展示的信息仅用于屏幕信息展示，不构成任何投资建议或交易依据。"),
    ("RiskAiTitle", "AI usage: a note", "Витрати AI: примітка", "AI 用量功能提示"),
    ("RiskAiHeading", "Tokscale local data source", "Локальне джерело даних Tokscale", "Tokscale 本地数据源"),
    ("RiskAiBody",
     "This feature relies on Tokscale, an open-source tool you install yourself. KSS only calls Tokscale's JSON commands locally: it does not take over account sign-in, does not read API keys, and never uploads usage or credentials. How complete the numbers are varies by client and platform, so treat them as personal information display only.",
     "Ця функція спирається на Tokscale — відкритий інструмент, який ви встановлюєте самостійно. KSS лише локально викликає JSON-команди Tokscale: не керує входом в акаунти, не читає API-ключі й нікуди не надсилає дані про використання чи облікові дані. Повнота статистики залежить від клієнта та платформи, тому вважайте її суто інформаційною.",
     "此功能依赖用户自行安装的开源工具 Tokscale。KSS 只在本机调用 Tokscale 的 JSON 命令，不接管账号登录、不读取 API Key，也不会上传用量或凭据。不同客户端与平台的统计完整度可能不同，数据仅供个人信息展示。"),
    ("PickImageTitle", "Choose a screen image", "Оберіть зображення для екрана", "选择屏幕图片"),
    ("PickImageFileType", "Images", "Зображення", "图片"),

    # ---- toggle switch content ------------------------------------------------
    ("ToggleOn", "On", "Увімк.", "启用"),
    ("ToggleOff", "Off", "Вимк.", "关闭"),

    # ---- view-model status ----------------------------------------------------
    ("StatusDisconnected", "Disconnected", "Немає зв'язку", "断开连接"),
    ("StatusOnline", "Device online", "Пристрій онлайн", "设备在线"),
    ("DeviceNotConfigured", "No address set", "Адресу не вказано", "地址未配置"),
    ("SourceReading", "Reading data…", "Читаю дані…", "正在读取数据…"),
    ("LastUpdatedNever", "Not refreshed yet", "Ще не оновлювалося", "尚未刷新"),
    ("LastUpdatedRefreshing", "Refreshing", "Оновлення", "正在刷新"),
    ("LastUpdatedAt", "Updated at {0}", "Оновлено о {0}", "更新于 {0}"),
    ("RefreshFailed", "Refresh failed: {0}", "Не вдалося оновити: {0}", "刷新失败：{0}"),
    ("DurationSeconds", "{0} s", "{0} с", "{0} 秒"),
    ("DurationMinutes", "{0} min", "{0} хв", "{0} 分钟"),
    ("DurationHours", "{0} h", "{0} год", "{0} 小时"),
    ("UpdateChecking", "Checking for updates…", "Перевіряю оновлення…", "正在检查更新…"),
    ("UpdateCheckFailed", "Check failed ({0}). Try again.", "Перевірка не вдалася ({0}). Спробуйте ще раз.", "检查失败（{0}），请重试"),
    ("UpdateAvailable", "New version {0} available", "Доступна нова версія {0}", "发现新版本 {0}"),
    ("UpdateUpToDate", "You are on the latest version", "У вас найновіша версія", "已是最新版本"),
    ("ThemeGroupComposer", "Builder", "Конструктор", "自定义"),
    ("ThemeGroupMonitoring", "Monitoring", "Моніторинг", "监控"),
    ("ThemeGroupTime", "Time", "Час", "时间"),
    ("ThemeGroupInfo", "Info", "Інформація", "资讯"),
    ("ThemeGroupMusic", "Music", "Музика", "音乐"),
    ("ThemeGroupDotMatrix", "Dot matrix", "Точкова матриця", "点阵"),
    ("SummarySystem", "CPU {0}% · Memory {1}% · Down {2}M · Up {3}M", "CPU {0}% · Пам'ять {1}% · Завант. {2}M · Вивант. {3}M", "CPU {0}% · 内存 {1}% · 下载 {2}M · 上传 {3}M"),
    ("SummaryMusic", "{0} · {1} — {2}", "{0} · {1} — {2}", "{0} · {1} — {2}"),
    ("SummaryNoMediaSession", "No Windows media session is available", "Немає доступної медіасесії Windows", "当前没有可用的 Windows 媒体会话"),
    ("SummaryWeather", "{0} · {1}° · {2}", "{0} · {1}° · {2}", "{0} · {1}° · {2}"),
    ("SummaryNoWeather", "No weather data", "Немає даних про погоду", "暂无天气数据"),
    ("SummaryStocks", "{0} quotes · updated {1}", "{0} котирувань · оновлено {1}", "{0} 项行情 · 更新 {1}"),
    ("SummaryConfigureStocks", "Add stock symbols first", "Спершу додайте коди акцій", "请先配置股票代码"),
    ("SummaryNoTokscaleData", "No Tokscale data read yet", "Дані Tokscale ще не прочитано", "尚未读取 Tokscale 数据"),
    ("SummaryLocalOnly", "This theme uses only local time and settings", "Ця тема використовує лише місцевий час і налаштування", "此主题仅使用本地时间与设置"),
    ("LoadingSystem", "Reading PC status…", "Читаю стан ПК…", "正在读取电脑状态…"),
    ("LoadingMusic", "Reading media status…", "Читаю стан медіа…", "正在读取媒体状态…"),
    ("LoadingWeather", "Reading weather data…", "Читаю дані про погоду…", "正在读取天气数据…"),
    ("LoadingStocks", "Reading stock quotes…", "Читаю котирування акцій…", "正在读取股票行情…"),
    ("LoadingAiUsage", "Reading AI usage…", "Читаю витрати AI…", "正在读取 AI 用量…"),
    ("LoadingTheme", "Refreshing theme data…", "Оновлюю дані теми…", "正在刷新主题数据…"),

    # ---- value converters -----------------------------------------------------
    ("ImagePlacementTop", "Top", "Зверху", "显示在上方"),
    ("ImagePlacementBottom", "Bottom", "Знизу", "显示在下方"),
    ("PeriodToday", "Today", "Сьогодні", "今天"),
    ("PeriodWeek", "This week", "Цей тиждень", "本周"),
    ("PeriodMonth", "This month", "Цей місяць", "本月"),
    ("PeriodQuarter", "This quarter", "Цей квартал", "本季度"),
    ("PeriodYear", "This year", "Цей рік", "本年"),
    ("ClockStyleDigital", "Digital", "Цифровий", "数字时钟"),
    ("ClockStyleLargeDigital", "Large digital", "Великі цифри", "大数字时间"),
    ("ClockStyleAnalog", "Analog", "Стрілковий", "模拟时钟"),
    ("ClockStyleFlip", "Flip", "Перекидний", "翻页时钟"),
    ("ImageTextColorLight", "Light", "Світлий", "浅色模式"),
    ("ImageTextColorDark", "Dark", "Темний", "暗色模式"),
    ("AlignLeft", "Left", "Ліворуч", "左对齐"),
    ("AlignCenter", "Center", "По центру", "居中对齐"),
    ("AlignRight", "Right", "Праворуч", "右对齐"),
    ("OrderTime", "Time", "Час", "时间"),
    ("OrderDate", "Date", "Дата", "日期"),
    ("OrderWeather", "Weather", "Погода", "天气"),
    ("OrderClock", "Clock", "Годинник", "时钟"),
    ("UiThemeLight", "Light", "Світла", "亮色模式"),
    ("UiThemeDark", "Dark", "Темна", "暗色模式"),
    ("UiThemeSystem", "System", "Як у системі", "跟随系统"),

    # ---- macOS build only (its pages differ from the Windows build) -----------
    ("MacStocksHint",
     "Add up to three. Supports symbols such as AAPL, 0700.HK, 600519.SS, 000001.SZ and BTC-USD. Data may be delayed or inaccurate and is not investment advice.",
     "Можна додати до трьох. Підтримуються коди на кшталт AAPL, 0700.HK, 600519.SS, 000001.SZ і BTC-USD. Дані можуть бути із затримкою або неточними й не є інвестиційною порадою.",
     "最多添加三项。支持 AAPL、0700.HK、600519.SS、000001.SZ、BTC-USD 等代码；数据可能延迟或不准确，不构成投资建议。"),
    ("MacAiQuotaPendingHint",
     "Reading the signed-in account needs a browser session; it arrives with the Windows WebView work.",
     "Читання даних облікового запису потребує сесії браузера — з'явиться разом із роботою над Windows WebView.",
     "登录读取依赖浏览器会话，将在 Windows WebView 适配阶段接入。"),
    ("MacAiQuotaPending",
     "MiMo sign-in reading arrives with the Windows WebView work",
     "Читання даних входу MiMo з'явиться разом із роботою над Windows WebView",
     "MiMo 登录读取将在 Windows WebView 适配阶段接入"),
    ("MacRefreshHint",
     "The refresh interval is 1-30 seconds. Changes save and push immediately.",
     "Інтервал оновлення — 1–30 секунд. Зміни зберігаються й надсилаються одразу.",
     "刷新间隔为 1–30 秒，设置变更会立即保存并推送。"),
    ("MacAboutDataSourcesNote",
     "Weather data comes from Open-Meteo; auto-detected city names are resolved by BigDataCloud. The Yahoo Finance quotes and Xiaomi MiMo usage are unofficial, experimental integrations that may be delayed, inaccurate or stop working; stock information is not investment advice. Keyboard Screen Studio is an independent personal project with no affiliation with, authorization from, endorsement by or sponsorship from the Linx68 device manufacturer or any of the platforms above. The app and tray icons are original AI-assisted visual assets - see ASSET_LICENSE.md.",
     "Дані про погоду надає Open-Meteo, назви автоматично визначених міст — BigDataCloud. Котирування Yahoo Finance і дані Xiaomi MiMo — неофіційні експериментальні інтеграції, які можуть запізнюватися, бути неточними або перестати працювати; інформація про акції не є інвестиційною порадою. Keyboard Screen Studio — незалежний особистий проєкт, не пов'язаний із виробником пристрою Linx68 чи згаданими платформами й не має від них дозволу, схвалення чи спонсорства. Іконки програми та трея — оригінальні візуальні матеріали, створені за допомогою AI; див. ASSET_LICENSE.md.",
     "天气数据由 Open-Meteo 提供，自动定位城市名由 BigDataCloud 解析。Yahoo Finance 行情与 Xiaomi MiMo 用量均为非官方实验性集成，可能延迟、不准确或失效；股票信息不构成投资建议。Keyboard Screen Studio 是独立个人项目，与 Linx68 设备制造商及上述平台不存在隶属、授权、认可或赞助关系。应用与托盘图标为 AI 辅助创作的原创视觉资产，详见 ASSET_LICENSE.md。"),

    # ---- Claude limits settings ----------------------------------------------
    ("ClaudeHeading", "Claude limits", "Ліміти Claude", "Claude 额度"),
    ("ClaudeSessionKeyLabel", "Session key", "Ключ сесії", "会话密钥"),
    ("ClaudeSessionKeyPlaceholder", "sessionKey cookie from claude.ai", "кука sessionKey із claude.ai", "来自 claude.ai 的 sessionKey"),
    ("ClaudeSessionKeyHint",
     "Open claude.ai signed in, copy the sessionKey cookie and paste it here. It is stored on this machine and sent to claude.ai only.",
     "Відкрийте claude.ai під своїм акаунтом, скопіюйте куку sessionKey і вставте сюди. Вона зберігається на цьому комп'ютері й надсилається лише на claude.ai.",
     "登录 claude.ai 后复制 sessionKey Cookie 并粘贴到此处。它仅保存在本机，且只发送到 claude.ai。"),
    ("ClaudeModelScopeLabel", "Model row", "Рядок моделі", "模型行"),
    ("ClaudeModelScopeHint", "Whose weekly window the third meter shows.", "Тижневе вікно якої моделі показує третя смуга.", "第三条量表显示哪个模型的每周窗口。"),
    ("ClaudeCountTokensLabel", "Count local tokens", "Рахувати локальні токени", "统计本机 Token"),
    ("ClaudeCountTokensHint",
     "Sums the Claude Code transcripts on this computer. A floor on real usage, never the account total.",
     "Підсумовує транскрипти Claude Code на цьому комп'ютері. Це нижня межа реального використання, а не підсумок акаунта.",
     "汇总本机的 Claude Code 记录。这是实际用量的下限，并非账户总量。"),
    ("LoadingClaude", "Reading Claude limits…", "Читаю ліміти Claude…", "正在读取 Claude 额度…"),
    ("SummaryClaudeNotConfigured", "Add a claude.ai session key", "Додайте ключ сесії claude.ai", "请添加 claude.ai 会话密钥"),
    ("SummaryClaude", "Session {0}% · week {1}%", "Сесія {0}% · тиждень {1}%", "会话 {0}% · 本周 {1}%"),
    ("RiskClaudeTitle", "Claude limits: a note", "Ліміти Claude: примітка", "Claude 额度提示"),
    ("RiskClaudeHeading", "Unofficial claude.ai integration", "Неофіційна інтеграція з claude.ai", "非官方 claude.ai 集成"),
    ("RiskClaudeBody",
     "This reads your limits from claude.ai with a session cookie you paste in yourself. The key is kept in this machine's settings file as plain text and is sent to claude.ai and nowhere else - treat it like a password, and clear it if anyone else uses this computer. The usage endpoint is unofficial and can change or stop working without notice. Token counts come from the Claude Code transcripts on this computer only, so they are a floor on your real usage, not your account total.",
     "Ця функція читає ваші ліміти з claude.ai за кукою сесії, яку ви вставляєте самі. Ключ зберігається у файлі налаштувань цього комп'ютера у відкритому вигляді й надсилається лише на claude.ai - поводьтеся з ним як із паролем і приберіть його, якщо комп'ютером користується ще хтось. Ендпоінт використання неофіційний і може змінитися чи перестати працювати без попередження. Токени беруться лише з транскриптів Claude Code на цьому комп'ютері, тож це нижня межа реального використання, а не підсумок акаунта.",
     "此功能使用您自行粘贴的会话 Cookie 从 claude.ai 读取额度。密钥以明文保存在本机的设置文件中，且只发送到 claude.ai — 请像对待密码一样对待它；如果他人也使用这台电脑，请清除它。该用量接口是非官方的，可能随时变更或失效。Token 数量仅来自本机的 Claude Code 记录，因此是实际用量的下限，而非账户总量。"),

    # ---- A7: how to obtain the claude.ai session cookie ------------------------
    ("ClaudeGuideHeading", "Where to find the key - three steps", "Де взяти ключ - три кроки", "如何获取密钥 - 三步"),
    ("ClaudeGuideStep1", "Open claude.ai and sign in", "Відкрийте claude.ai і увійдіть", "打开 claude.ai 并登录"),
    ("ClaudeGuideStep1Hint", "Any browser works", "Підійде будь-який браузер", "任意浏览器均可"),
    ("ClaudeGuideStep2", "Press F12 and find the cookies", "Натисніть F12 і знайдіть куки", "按 F12 找到 Cookie"),
    ("ClaudeGuideStep2Hint", "Application (Chrome/Edge) or Storage (Firefox) - Cookies - https://claude.ai", "Application (Chrome/Edge) або Storage (Firefox) - Cookies - https://claude.ai", "Application（Chrome/Edge）或 Storage（Firefox）- Cookies - https://claude.ai"),
    ("ClaudeGuideStep3", "Copy the sessionKey value and paste it above", "Скопіюйте значення sessionKey і вставте вище", "复制 sessionKey 的值并粘贴到上方"),
    ("ClaudeGuideStep3Hint", "It starts with sk-ant-sid01…", "Воно починається з sk-ant-sid01…", "以 sk-ant-sid01… 开头"),
    ("ClaudeOpenSite", "Open claude.ai", "Відкрити claude.ai", "打开 claude.ai"),

    # ---- A1: push diagnostics ---------------------------------------------------
    ("DiagnosticsHeading", "Push diagnostics", "Діагностика надсилання", "推送诊断"),
    ("DiagnosticsHint", "What the keyboard answered to the most recent pushes.", "Що клавіатура відповіла на останні надсилання.", "键盘对最近几次推送的响应。"),
    ("DiagnosticsLastPush", "Last push", "Останнє надсилання", "最近推送"),
    ("DiagnosticsLatency", "Latency", "Затримка", "延迟"),
    ("DiagnosticsFrameSize", "Frame size", "Розмір кадру", "帧大小"),
    ("DiagnosticsNoPushes", "Nothing has been pushed yet", "Ще нічого не надсилалося", "尚未推送任何内容"),
    ("DiagnosticsOk", "OK", "Успішно", "成功"),
    ("DiagnosticsFailed", "Failed", "Помилка", "失败"),
    ("DiagnosticsRecentErrors", "Recent errors", "Останні помилки", "最近错误"),
    ("DiagnosticsNoErrors", "No errors in the last pushes", "В останніх надсиланнях помилок немає", "最近的推送没有错误"),

    # ---- A6.1: Binance source ---------------------------------------------------
    ("StockSourceBinance", "Binance (crypto)", "Binance (крипто)", "币安（加密货币）"),

    # ---- A2: currency rates card ------------------------------------------------
    ("CurrencyHeading",    "Currency rates", "Курси валют", "汇率"),
    ("CurrencyHint",       "Daily reference rates from the open ExchangeRate-API feed; no key is required.",
                           "Щоденні довідкові курси з відкритого фіду ExchangeRate-API; ключ не потрібен.",
                           "来自开放 ExchangeRate-API 源的每日参考汇率，无需密钥。"),
    ("CurrencyBaseLabel",  "Base currency", "Базова валюта", "基准货币"),
    ("CurrencyQuotesLabel","Show rates for", "Показувати курси", "显示汇率"),
    ("CurrencyQuotesHint", "Comma-separated ISO codes, e.g. EUR, UAH, PLN. Up to four fit on the screen.",
                           "Коди ISO через кому, напр. EUR, UAH, PLN. На екран вміщується до чотирьох.",
                           "以逗号分隔的 ISO 代码，如 EUR, UAH, PLN。屏幕最多显示四个。"),
    ("SummaryCurrency",          "{0} rates vs {1} · updated {2}", "{0} курсів до {1} · оновлено {2}", "{0} 项兑 {1} 汇率 · 更新 {2}"),
    ("SummaryConfigureCurrency", "Add currency codes first", "Спершу додайте коди валют", "请先配置货币代码"),
    ("LoadingCurrency",          "Reading exchange rates…", "Читаю курси валют…", "正在读取汇率…"),

    # ---- A6.2: crypto card --------------------------------------------------------
    ("CryptoHeading", "Crypto", "Крипто", "加密货币"),
    ("CryptoHint",    "Binance pairs such as BTCUSDT (BTC-USD works too). Two to four coins; prices are quoted in USDT.",
                      "Пари Binance, напр. BTCUSDT (BTC-USD теж працює). Від двох до чотирьох монет; ціни в USDT.",
                      "币安交易对，如 BTCUSDT（也支持 BTC-USD）。2-4 种币，价格以 USDT 计。"),
    ("CryptoPairLabel",  "Pairs", "Пари", "交易对"),
    ("SummaryCrypto",          "{0} coins · updated {1}", "{0} монет · оновлено {1}", "{0} 种币 · 更新 {1}"),
    ("SummaryConfigureCrypto", "Add Binance pairs first", "Спершу додайте пари Binance", "请先配置币安交易对"),
    ("LoadingCrypto",          "Reading Binance prices…", "Читаю ціни Binance…", "正在读取币安价格…"),

    # ---- A4: pomodoro card --------------------------------------------------------
    ("PomodoroHeading",     "Pomodoro", "Помодоро", "番茄钟"),
    ("PomodoroHint",        "The timer runs on the wall clock, so it stays correct through restarts and sleep.",
                            "Таймер прив'язаний до годинника, тому лишається точним після перезапусків і сну.",
                            "计时基于系统时钟，重启或休眠后依然准确。"),
    ("PomodoroFocusLabel",  "Focus, minutes", "Фокус, хвилин", "专注（分钟）"),
    ("PomodoroBreakLabel",  "Break, minutes", "Перерва, хвилин", "休息（分钟）"),
    ("PomodoroCyclesLabel", "Cycles", "Циклів", "循环次数"),
    ("PomodoroStart",       "Start", "Старт", "开始"),
    ("PomodoroStop",        "Stop", "Стоп", "停止"),
    ("SummaryPomodoroIdle",    "Timer stopped", "Таймер зупинено", "计时器已停止"),
    ("SummaryPomodoroPhase",   "{0} · {1} left", "{0} · залишилось {1}", "{0} · 剩余 {1}"),
    ("TrayPomodoroToggle",  "Start / stop Pomodoro", "Старт / стоп помодоро", "开始 / 停止番茄钟"),

    # ---- A3: night schedule card --------------------------------------------------
    ("ScheduleHeading",     "Night schedule", "Нічний розклад", "夜间计划"),
    ("ScheduleHint",        "At night the screen can switch to another theme and dim the render.",
                            "Уночі екран може перемикатися на іншу тему та зменшувати яскравість.",
                            "夜间屏幕可切换到其他主题并降低亮度。"),
    ("ScheduleNightStartLabel", "Night starts", "Початок ночі", "夜间开始"),
    ("ScheduleNightEndLabel",   "Night ends", "Кінець ночі", "夜间结束"),
    ("ScheduleTimeHint",    "24-hour HH:mm, e.g. 22:00; the window may cross midnight.",
                            "24-годинний формат HH:mm, напр. 22:00; вікно може переходити через північ.",
                            "24 小时制 HH:mm，如 22:00；时段可跨越午夜。"),
    ("ScheduleSwitchThemeLabel", "Switch theme at night", "Перемикати тему вночі", "夜间切换主题"),
    ("ScheduleNightThemeLabel",  "Night theme", "Нічна тема", "夜间主题"),
    ("ScheduleDimLabel",         "Dim the screen at night", "Зменшувати яскравість уночі", "夜间降低亮度"),
    ("ScheduleBrightnessLabel",  "Night brightness", "Нічна яскравість", "夜间亮度"),
    ("ScheduleMediaNote",   "While music plays, media automation outranks the schedule.",
                            "Під час відтворення музики медіа-автоматика має пріоритет над розкладом.",
                            "播放音乐时，媒体自动化优先于计划。"),
    # ---- A9: hardware monitor card ------------------------------------------------
    ("HardwareHeading", "Hardware monitor", "Апаратний монітор", "硬件监控"),
        ("HardwareHint",
     "Sensor data comes from the bundled LibreHardwareMonitor library. CPU temperature usually appears only when the app runs as administrator; anything unavailable shows an em dash.",
     "Дані сенсорів надає вбудована бібліотека LibreHardwareMonitor. Температура CPU зазвичай з'являється лише із запуском від адміністратора; недоступні показники позначаються тире.",
     "传感器数据由内置的 LibreHardwareMonitor 库提供。CPU 温度通常需要以管理员身份运行才会显示；不可用的读数显示为破折号。"),
    ("HardwarePageSecondsLabel", "Seconds per page", "Секунд на сторінку", "每页秒数"),
    ("SummaryHardware", "CPU {0} · GPU {1} · updated {2}", "CPU {0} · GPU {1} · оновлено {2}", "CPU {0} · GPU {1} · 更新 {2}"),

    # ---- A5: GitHub activity card -------------------------------------------------
    ("GitHubHeading",       "GitHub activity", "Активність GitHub", "GitHub 活动"),
        ("GitHubHint",
     "The public contribution graph needs only a username. An optional fine-grained token adds private contributions.",
     "Для публічного графіка контрибуцій досить імені користувача. Необов'язковий fine-grained токен додає приватні контрибуції.",
     "公开贡献图只需用户名。可选的细粒度令牌可统计私有贡献。"),
        ("GitHubUsernameLabel",
     "Username",
     "Ім'я користувача",
     "用户名"),
        ("GitHubTokenLabel",
     "Access token (optional)",
     "Токен доступу (необов'язково)",
     "访问令牌（可选）"),
    ("SummaryGitHub",          "@{0}: {1} this week · updated {2}", "@{0}: {1} за тиждень · оновлено {2}", "@{0}：本周 {1} · 更新 {2}"),
        ("SummaryConfigureGitHub",
     "Add a GitHub username first",
     "Спершу вкажіть ім'я користувача GitHub",
     "请先填写 GitHub 用户名"),

    # ---- A8: Telegram popups card -------------------------------------------------
    ("TelegramHeading", "Telegram on the screen", "Telegram на екрані", "屏幕上的 Telegram"),
    ("TelegramHint",    "Incoming messages from your personal Telegram account pop up on the keyboard screen for a few seconds, over whatever theme is showing.",
                        "Вхідні повідомлення вашого особистого акаунта Telegram спливають на екрані клавіатури на кілька секунд поверх будь-якої теми.",
                        "个人 Telegram 账号的新消息会在键盘屏上弹出几秒，覆盖在当前主题之上。"),
    ("TelegramGuideHeading", "Getting api_id and api_hash", "Як отримати api_id та api_hash", "获取 api_id 与 api_hash"),
    ("TelegramGuideStep1",     "Open my.telegram.org", "Відкрийте my.telegram.org", "打开 my.telegram.org"),
    ("TelegramGuideStep1Hint", "Sign in with your phone number", "Увійдіть за номером телефону", "使用手机号登录"),
    ("TelegramGuideStep2",     "API development tools", "API development tools", "API development tools"),
    ("TelegramGuideStep2Hint", "Create an app - any name and short name will do", "Створіть застосунок - назва може бути будь-якою", "创建应用，名称任意"),
    ("TelegramGuideStep3",     "Copy api_id and api_hash below", "Скопіюйте api_id та api_hash сюди", "将 api_id 和 api_hash 复制到下方"),
    ("TelegramGuideStep3Hint", "Then connect with your phone number", "Далі підключіться за номером телефону", "然后用手机号连接"),
    ("TelegramApiIdLabel",   "api_id", "api_id", "api_id"),
    ("TelegramApiHashLabel", "api_hash", "api_hash", "api_hash"),
    ("TelegramPhoneLabel",   "Phone number", "Номер телефону", "手机号"),
    ("TelegramPhonePlaceholder", "+380501234567", "+380501234567", "+8613800138000"),
    ("TelegramConnect",     "Connect", "Підключити", "连接"),
    ("TelegramCodeLabel",   "Code from Telegram", "Код із Telegram", "Telegram 验证码"),
    ("TelegramCodeSubmit",  "Confirm code", "Підтвердити код", "确认验证码"),
    ("TelegramPasswordLabel","Two-step password", "Пароль двоетапної перевірки", "两步验证密码"),
    ("TelegramPasswordSubmit","Confirm password", "Підтвердити пароль", "确认密码"),
    ("TelegramLogout",      "Log out and wipe the session", "Вийти і стерти сесію", "退出并清除会话"),
    ("TelegramStateDisconnected", "Not connected", "Не підключено", "未连接"),
    ("TelegramStateConnecting",   "Connecting…", "Підключення…", "连接中…"),
    ("TelegramStateWaitingCode",  "Enter the code Telegram just sent you", "Введіть код, який щойно надіслав Telegram", "请输入 Telegram 刚发送的验证码"),
    ("TelegramStateWaitingPassword","Enter your two-step verification password", "Введіть пароль двоетапної перевірки", "请输入两步验证密码"),
    ("TelegramStateConnected",    "Connected - messages will pop up on the screen", "Підключено - повідомлення спливатимуть на екрані", "已连接 - 新消息将弹出在屏幕上"),
    ("TelegramStateFailed",       "Connection failed: {0}", "Не вдалося підключитися: {0}", "连接失败：{0}"),
    ("TelegramPopupsEnabledLabel", "Show popups on the screen", "Показувати попапи на екрані", "在屏幕上显示弹窗"),
    ("TelegramPrivacyLabel", "What a popup shows", "Що показує попап", "弹窗显示内容"),
    ("TelegramPrivacyCounter",       "Count only", "Лише кількість", "仅显示数量"),
        ("TelegramPrivacySender",
     "Sender name only",
     "Лише ім'я відправника",
     "仅显示发送者"),
        ("TelegramPrivacySenderPreview",
     "Sender and text preview",
     "Ім'я і прев'ю тексту",
     "发送者与文本预览"),
    ("TelegramPopupSecondsLabel", "Popup duration, seconds", "Тривалість попапа, секунд", "弹窗时长（秒）"),
    ("TelegramMutedNote", "Muted chats never pop up.", "Заглушені чати не спливають.", "已静音的对话不会弹出。"),
    ("TelegramMediaMessage", "[media]", "[медіа]", "[媒体]"),
    # ---- A8b: desktop notifications card ------------------------------------------
    ("NotifyHeading", "Desktop notifications", "Сповіщення на робочому столі", "桌面通知"),
    ("NotifyHint",    "Windows toast notifications for app events. Each trigger has a cooldown, so nothing spams.",
                      "Windows-сповіщення про події застосунку. Кожен тригер має кулдаун, тож нічого не спамить.",
                      "应用事件的 Windows 通知。每个触发器都有冷却时间，不会刷屏。"),
    ("NotifyClaudeLabel", "Claude limits at 80 / 90 / 95%", "Ліміти Claude на 80 / 90 / 95%", "Claude 额度达到 80 / 90 / 95%"),
    ("NotifyClaudeSub",   "Needs the claude.ai key from the Claude theme.", "Потрібен ключ claude.ai з теми Claude.", "需要 Claude 主题的 claude.ai 密钥。"),
    ("NotifyOfflineLabel", "Keyboard went offline", "Клавіатура офлайн", "键盘离线"),
    ("NotifyOfflineSub",   "When a push to the screen starts failing.", "Коли надсилання на екран починає падати.", "推送屏幕开始失败时提醒。"),
    ("NotifyPriceHeading", "Binance price alerts", "Цінові алерти Binance", "币安价格提醒"),
    ("NotifyPriceHint",    "Fires when the price crosses a bound; re-arms after it returns.",
                           "Спрацьовує на перетині межі; знову озброюється після повернення ціни.",
                           "价格越界时提醒；回到界内后重新武装。"),
    ("NotifyPriceSymbol",  "Pair", "Пара", "交易对"),
    ("NotifyPriceAboveLabel", "Above", "Вище", "高于"),
    ("NotifyPriceBelowLabel", "Below", "Нижче", "低于"),
        ("NotifyWindowsOnly",
     "Notifications appear on Windows 10/11 only.",
     "Сповіщення з'являються лише у Windows 10/11.",
     "通知仅在 Windows 10/11 上显示。"),
    ("NotifyClaudeTitle", "Claude limits", "Ліміти Claude", "Claude 额度"),
    ("NotifyClaudeBody",  "{0} is at {1}%", "{0}: вже {1}%", "{0} 已达 {1}%"),
    ("NotifyClaudeSession",   "The 5-hour session window", "5-годинне вікно сесії", "5 小时会话窗口"),
    ("NotifyClaudeWeek",      "The weekly window", "Тижневе вікно", "每周窗口"),
    ("NotifyClaudeModelWeek", "The weekly model window", "Тижневе вікно моделі", "每周模型窗口"),
    ("NotifyDeviceOfflineTitle", "Keyboard screen offline", "Екран клавіатури офлайн", "键盘屏离线"),
        ("NotifyDeviceOfflineBody",
     "Pushes to the keyboard screen are failing - check the connection and the Image API mode.",
     "Надсилання на екран клавіатури не проходять - перевірте з'єднання і режим Image API.",
     "推送键盘屏失败 - 请检查连接和 Image API 模式。"),
    ("NotifyPriceTitle", "{0} price alert", "Ціновий алерт {0}", "{0} 价格提醒"),
    ("NotifyPriceAbove", "{0} is at {1}, above your {2} bound", "{0}: ціна {1}, вище вашої межі {2}", "{0} 现价 {1}，高于您设定的 {2}"),
    ("NotifyPriceBelow", "{0} is at {1}, below your {2} bound", "{0}: ціна {1}, нижче вашої межі {2}", "{0} 现价 {1}，低于您设定的 {2}"),
    # ---- B5: settings export/import card ------------------------------------------
    ("PortHeading", "Settings backup", "Резервна копія налаштувань", "设置备份"),
        ("PortHint",
     "Export writes every setting to a JSON file with the secrets removed - the claude.ai key, the GitHub token and the Telegram credentials never leave this machine. Import keeps the secrets already stored here.",
     "Експорт записує всі налаштування у JSON-файл без секретів - ключ claude.ai, токен GitHub і облікові дані Telegram не залишають цей комп'ютер. Імпорт зберігає секрети, які вже є тут.",
     "导出会把全部设置写入 JSON 文件并移除机密信息 - claude.ai 密钥、GitHub 令牌和 Telegram 凭据不会离开本机。导入会保留本机已有的机密信息。"),
    ("PortExport", "Export settings…", "Експортувати налаштування…", "导出设置…"),
    ("PortImport", "Import settings…", "Імпортувати налаштування…", "导入设置…"),
    ("PortExportedTo", "Exported to {0}", "Експортовано у {0}", "已导出到 {0}"),
    ("PortImportDone", "Settings imported", "Налаштування імпортовано", "设置已导入"),
    ("PortFailed", "Failed: {0}", "Не вдалося: {0}", "失败：{0}"),
    ("PortImportInvalid", "The file is not a valid settings export", "Файл не є коректним експортом налаштувань", "该文件不是有效的设置导出"),
    ("PortJsonFileType", "Settings JSON", "JSON налаштувань", "设置 JSON"),
    # ---- B1: theme carousel card --------------------------------------------------
    ("CarouselHeading", "Theme carousel", "Карусель тем", "主题轮播"),
    ("CarouselHint",    "Rotates the screen through the checked themes. Media automation and the night schedule still take priority when active.",
                        "По черзі показує позначені теми. Медіа-автоматика та нічний розклад зберігають пріоритет, коли активні.",
                        "在勾选的主题之间轮播。媒体自动化与夜间计划在生效时仍然优先。"),
    ("CarouselIntervalLabel", "Seconds per theme", "Секунд на тему", "每个主题秒数"),
    ("CarouselPickHint", "Check at least two themes.", "Позначте щонайменше дві теми.", "请至少勾选两个主题。"),
    # ---- B3: display units card ---------------------------------------------------
    ("UnitsHeading", "Units", "Одиниці", "单位"),
    ("Units12Hour",  "12-hour clock", "12-годинний формат", "12 小时制"),
    ("Units12HourHint", "The small screen shows no AM/PM marker - only the digits change.",
                        "На маленькому екрані немає позначки AM/PM - змінюються лише цифри.",
                        "小屏不显示 AM/PM 标记 - 仅数字变化。"),
    ("UnitsFahrenheit", "Fahrenheit", "Фаренгейт", "华氏度"),
    ("UnitsFahrenheitHint", "Applies to weather and hardware temperatures.",
                            "Стосується погоди й температур обладнання.",
                            "适用于天气与硬件温度。"),
    # ---- per-theme refresh interval -----------------------------------------------
    ("ThemeRefreshHeading", "Refresh interval, seconds", "Інтервал оновлення, секунд", "刷新间隔（秒）"),
    ("ThemeRefreshHint",    "How often this theme re-renders and pushes. Clocks want every second; data screens default to a slower pace, and the header clock still flips on the minute.",
                            "Як часто ця тема перемальовується і надсилається. Годинникам потрібна кожна секунда; інформаційні екрани типово повільніші, а годинник у шапці все одно перемикається рівно на хвилині.",
                            "此主题重绘并推送的频率。时钟需要每秒刷新；数据屏默认较慢，标题栏时钟仍会准点跳分。"),

    # ---- B11: air alerts card -----------------------------------------------------
    ("AlertsHeading", "Air alerts", "Повітряні тривоги", "空袭警报"),
    ("AlertsHint",    "Data comes from the community alerts.in.ua API and refreshes every half minute. This screen is informational, with inherent delays - never your only warning source.",
                      "Дані надходять із громадського API alerts.in.ua та оновлюються кожні пів хвилини. Цей екран - лише інформаційний, із неминучими затримками; ніколи не єдине джерело оповіщення.",
                      "数据来自社区 alerts.in.ua API，每半分钟刷新。此屏幕仅供参考，存在固有延迟 - 切勿作为唯一警报来源。"),
    ("AlertsTokenLabel",    "API token", "API-токен", "API 令牌"),
        ("AlertsTokenHint",
     "Request a free token at alerts.in.ua; it is stored on this machine and sent only to that service.",
     "Отримайте безплатний токен на alerts.in.ua; він зберігається на цьому комп'ютері й надсилається лише цьому сервісу.",
     "在 alerts.in.ua 申请免费令牌；令牌保存在本机，仅发送给该服务。"),
    ("AlertsOpenSite",      "Open alerts.in.ua", "Відкрити alerts.in.ua", "打开 alerts.in.ua"),
    ("AlertsLocationLabel", "Location", "Локація", "地区"),
    ("AlertsLocationHint",  "Pick the region to watch; district- and city-level alerts inside it count too. The whole-country option shows the national summary.",
                            "Оберіть регіон для відстеження; тривоги районів і міст у ньому теж враховуються. Варіант «Вся Україна» показує зведення по країні.",
                            "选择要关注的地区；其下的区、市级警报同样计入。“全国”选项显示全国概览。"),
    ("AlertsRegionWholeCountry", "Whole country (summary)", "Вся Україна (зведення)", "全国（概览）"),
    ("AlertsTakeoverHeading", "Alert priority", "Пріоритет тривоги", "警报优先"),
    ("AlertsTakeoverHint",
     "When an alert starts in the selected region, the screen shows it by itself - even if this theme is not selected and is not in the carousel. The all-clear stays visible for a minute before the screen returns.",
     "Коли у вибраному регіоні починається тривога, екран сам показує її - навіть якщо ця тема не вибрана і її немає в каруселі. Після відбою екран ще хвилину показує «відбій», потім повертається.",
     "所选地区响起警报时，即使当前未选中此主题、也不在轮播中，屏幕也会自动显示警报。警报解除后再显示一分钟，然后恢复原主题。"),
    ("AlertsTakeoverModeLabel", "Display as", "Показувати як", "显示方式"),
    ("AlertsTakeoverOff",        "Off", "Вимкнено", "关闭"),
    ("AlertsTakeoverFullScreen", "Full screen", "На весь екран", "全屏"),
    ("AlertsTakeoverPopup",      "Popup banner (like Telegram)", "Попап-банер (як у Telegram)", "弹窗横幅（类似 Telegram）"),
    ("AlertsTakeoverUntilClearLabel", "Show until the all-clear", "Показувати до відбою", "显示到警报解除"),
    ("AlertsTakeoverMinutesLabel",    "Show for (minutes)", "Показувати (хвилин)", "显示时长（分钟）"),

    # ---- B2-B13 cards ------------------------------------------------------------
    ("ThemeAccentHeading",  "Theme accent", "Акцент теми", "主题强调色"),
    ("ThemeAccentHint",     "This theme can keep its own accent color; without one it follows the global accent from the Screen page.",
                            "Ця тема може мати власний акцентний колір; без нього діє глобальний акцент зі сторінки «Екран».",
                            "此主题可拥有自己的强调色；未设置时使用“屏幕”页的全局强调色。"),
    ("ThemeAccentPick",     "Choose color", "Обрати колір", "选择颜色"),
    ("ThemeAccentReset",    "Use global", "Глобальний", "使用全局"),
    ("WorldClockHeading",   "World clocks", "Світові годинники", "世界时钟"),
        ("WorldClockHint",
     "Up to four places. The label is free text; the time zone is an IANA name such as Europe/Kyiv, America/New_York or Asia/Tokyo.",
     "До чотирьох місць. Назва - довільний текст; часовий пояс - ім'я IANA, як-от Europe/Kyiv, America/New_York чи Asia/Tokyo.",
     "最多四地。名称为任意文本；时区使用 IANA 名称，如 Europe/Kyiv、America/New_York、Asia/Tokyo。"),
    ("WorldClockCityLabel", "Label", "Назва", "名称"),
    ("WorldClockZoneLabel", "Time zone", "Часовий пояс", "时区"),
    ("CountdownHeading",    "Countdown events", "Події відліку", "倒计时事件"),
    ("CountdownHint",       "Up to three events. Dates accept 2026-12-31, 31.12.2026, either with an optional time like 31.12.2026 18:30.",
                            "До трьох подій. Дати у форматі 2026-12-31 або 31.12.2026, за бажання з часом: 31.12.2026 18:30.",
                            "最多三个事件。日期格式为 2026-12-31 或 31.12.2026，可附时间：31.12.2026 18:30。"),
    ("CountdownTitleLabel", "Event", "Подія", "事件"),
    ("CountdownDateLabel",  "Date", "Дата", "日期"),
    ("PingHeading",         "Ping hosts", "Хости пінгу", "延迟主机"),
    ("PingHint",            "Up to four hosts by IP or name - the router, a DNS resolver, your server. Pinged with the theme's refresh interval.",
                            "До чотирьох хостів за IP чи іменем - роутер, DNS-резолвер, ваш сервер. Пінгуються з інтервалом оновлення теми.",
                            "最多四个主机（IP 或域名）——路由器、DNS、你的服务器。按主题刷新间隔发送 ping。"),
    ("CalendarHeading",     "Calendar feed", "Стрічка календаря", "日历订阅"),
    ("CalendarHint",        "Paste the calendar's ICS address (Google: Settings → Integrate calendar → Secret address; webcal:// links work too).",
                            "Вставте ICS-адресу календаря (Google: Налаштування → Інтеграція → Таємна адреса; посилання webcal:// теж працюють).",
                            "粘贴日历的 ICS 地址（Google：设置 → 整合日历 → 私密地址；webcal:// 链接同样可用）。"),
    ("CalendarUrlLabel",    "ICS address", "ICS-адреса", "ICS 地址"),
        ("CalendarUrlHint",
     "A private ICS link contains an access key, so it is stored on this machine, sent only to its own host, and stripped from settings exports.",
     "Приватне ICS-посилання містить ключ доступу, тому зберігається на цьому комп'ютері, надсилається лише своєму хосту і вирізається з експорту налаштувань.",
     "私密 ICS 链接含访问密钥：仅保存在本机、只发送到其所属主机，并会从设置导出中剔除。"),
    ("DevicesExtraLabel",   "More keyboards", "Додаткові клавіатури", "更多键盘"),
    ("DevicesExtraHint",    "Extra device addresses, comma-separated IPs or full endpoint URLs. Every frame is pushed to each of them too.",
                            "Додаткові адреси пристроїв - IP через кому або повні URL. Кожен кадр надсилається і на них.",
                            "额外的设备地址：逗号分隔的 IP 或完整 URL。每一帧也会推送到这些设备。"),
    ("DevicesExtraStatus",  "Extra devices: {0}/{1} ok", "Додаткові пристрої: {0}/{1} ок", "额外设备：{0}/{1} 正常"),
    ("StocksQuantityPlaceholder", "Qty", "К-сть", "数量"),
    ("StocksPortfolioHint", "Fill the quantity to see the portfolio value; symbols in different currencies are summed as-is, so mixing them makes the total meaningless.",
                            "Заповніть кількість, щоб бачити вартість портфеля; символи в різних валютах сумуються як є, тож змішувати їх - позбавляти суму сенсу.",
                            "填写数量后显示组合价值；不同货币的代码按原值相加，混用会使总额失去意义。"),
    ("SummaryCalendar",          "{0} upcoming · updated {1}", "Подій: {0} · оновлено {1}", "{0} 个日程 · 更新 {1}"),
    ("SummaryConfigureCalendar", "Add an ICS link first", "Спершу додайте ICS-посилання", "请先添加 ICS 链接"),
    ("LoadingCalendar",          "Reading the calendar…", "Читаю календар…", "正在读取日历…"),
    ("SummaryPing",              "Watching {0} host(s)", "Хостів: {0}", "监测 {0} 个主机"),
    ("SummaryDisks",             "{0} volume(s)", "Томів: {0}", "{0} 个磁盘"),
    ("SummaryWorldClock",        "{0} clock(s)", "Годинників: {0}", "{0} 个时钟"),
    ("SummaryCountdown",         "{0} event(s)", "Подій: {0}", "{0} 个事件"),

    # ---- currency source picker ---------------------------------------------------
    ("HardwareAdminHint",
     "CPU temperature and fan speeds come from the sensor driver, which needs the app to run as administrator. Load and frequency work without it.",
     "Температура CPU і оберти вентиляторів читаються через драйвер сенсорів - потрібен запуск застосунку від імені адміністратора. Навантаження і частота працюють і без нього.",
     "CPU 温度与风扇转速需要传感器驱动，须以管理员身份运行本应用。负载与频率无需管理员权限。"),
    ("HardwareRestartAdmin", "Restart as administrator", "Перезапустити від адміністратора", "以管理员身份重启"),
    ("HardwareSensorsUnsupported",
     "Running as administrator, and this board still reports no temperature",
     "Запущено від адміністратора, але ця плата все одно не віддає температуру",
     "已以管理员身份运行，但此主板仍不提供温度读数"),
    ("PerfVisualValuesLabel", "Numeric readout", "Цифрові значення", "数值显示"),
    ("PerfVisualValuesHint",
     "Shows the current figure on each panel next to its curve.",
     "Показує поточне число на кожній панелі поруч із кривою.",
     "在每个面板的曲线旁显示当前数值。"),
    ("HardwareLimitedSensors",
     "Limited sensors - run as administrator for temperatures and fans",
     "Обмежені сенсори - для температур і вентиляторів запустіть від імені адміністратора",
     "传感器受限——以管理员身份运行可读取温度与风扇"),

    # ---- knob theme switching -----------------------------------------------------
    ("KnobHeading",       "Keyboard knob", "Крутілка клавіатури", "键盘旋钮"),
    ("KnobHint",
     "Switch themes with the Linx68 volume knob: turn right for the next theme, left for the previous, press to pause or resume the carousel. Off by default.",
     "Перемикайте теми крутілкою гучності Linx68: поворот вправо - наступна тема, вліво - попередня, натиск - пауза/відновлення каруселі. За замовчуванням вимкнено.",
     "用 Linx68 音量旋钮切换主题：右旋下一主题，左旋上一主题，按下暂停/恢复轮播。默认关闭。"),
    ("KnobModeLabel",     "Input mode", "Режим вводу", "输入模式"),
    ("KnobModeVolume",    "Volume knob", "Крутілка гучності", "音量旋钮"),
    ("KnobModeHotKeys",   "Dedicated keys (F13-F24)", "Задані клавіші (F13-F24)", "专用按键（F13-F24）"),
    ("KnobSuppressLabel", "Mute the volume keys", "Гасити клавіші гучності", "拦截音量键"),
    ("KnobSuppressHint",
     "On: the knob only switches themes and the system volume stays put. Off: it does both at once.",
     "Увімкнено: крутілка лише перемикає теми, гучність системи не змінюється. Вимкнено: робить і те, і те одночасно.",
     "开：旋钮只切换主题，系统音量不变。关：两者同时生效。"),
    ("KnobVidPidLabel",   "Keyboard VID:PID", "VID:PID клавіатури", "键盘 VID:PID"),
        ("KnobVidPidHint",
     "Optional and blunt: a knob and the same keyboard's Fn volume keys share one VID:PID, so this binds the whole keyboard. Prefer detection below; empty reacts to any volume key.",
     "Необов'язково і грубо: крутілка й Fn-клавіші гучності тієї ж клавіатури мають спільний VID:PID, тож це прив'язує клавіатуру цілком. Краще скористайтеся визначенням нижче; порожнє поле реагує на будь-яку клавішу гучності.",
     "可选且较为笼统：旋钮与同一键盘的 Fn 音量键共用一个 VID:PID，因此这会绑定整块键盘。建议改用下面的检测；留空则响应任何音量键。"),
    ("KnobKeyForwardLabel",  "Next theme key", "Клавіша: наступна", "下一主题按键"),
    ("KnobKeyBackwardLabel", "Previous theme key", "Клавіша: попередня", "上一主题按键"),
    ("KnobKeyToggleLabel",   "Pause key", "Клавіша: пауза", "暂停按键"),
    ("KnobViaHint",
     "Cleanest with VIA/QMK: remap the encoder to F13/F14 and its press to F15 in the keyboard's configurator, pick the dedicated-keys mode here, and volume is never touched at all.",
     "Найчистіше через VIA/QMK: перепризначте енкодер на F13/F14, а натиск - на F15 у конфігураторі клавіатури, виберіть тут режим заданих клавіш - і гучність взагалі не зачіпається.",
     "最干净的方式是 VIA/QMK：在键盘配置器中把编码器改映射为 F13/F14、按下为 F15，在此选择专用按键模式，完全不影响音量。"),

    ("CurrencySourceLabel",  "Data source", "Джерело даних", "数据源"),
    ("CurrencySourceCdn",    "Currency-API (international, daily)", "Currency-API (міжнародне, щодня)", "Currency-API（国际，每日）"),
    ("CurrencySourceErApi",  "ExchangeRate-API (daily)", "ExchangeRate-API (щодня)", "ExchangeRate-API（每日）"),
    ("CurrencySourceNbu",    "NBU official rate (Ukraine)", "Офіційний курс НБУ", "乌克兰央行官方汇率"),
    ("CurrencySourceHint",   "If a rate looks off, switch the source - the screen's footer shows which day the data is for. The NBU option uses Ukraine's official daily rate, crossing other pairs through UAH.",
                             "Якщо курс виглядає неактуальним, змініть джерело - у нижньому рядку екрана видно, за який день дані. Варіант НБУ бере офіційний курс України, інші пари рахуються через гривню.",
                             "若汇率看起来不对，请切换数据源——屏幕底部会显示数据日期。NBU 选项使用乌克兰官方牌价，其他货币对通过格里夫纳换算。"),
    ("SummaryAlerts",          "{0} region(s) under alert · updated {1}", "{0} обл. у тривозі · оновлено {1}", "{0} 个地区警报 · 更新 {1}"),
    ("SummaryConfigureAlerts", "Add an alerts.in.ua token first", "Спершу додайте токен alerts.in.ua", "请先填写 alerts.in.ua 令牌"),
    ("LoadingAlerts",          "Reading alert status…", "Читаю стан тривог…", "正在读取警报状态…"),
    ("RiskAlertsTitle",   "Air alerts: a note", "Повітряні тривоги: примітка", "空袭警报提示"),
    ("RiskAlertsHeading", "Informational only", "Лише інформаційно", "仅供参考"),
        ("RiskAlertsBody",
     "This screen reads active alerts from the community alerts.in.ua API with a token you request yourself. The data passes through third-party infrastructure and arrives with delays of seconds to minutes; the app polls it every half minute. Treat it as a convenience display only - always rely on official sirens and government alert channels, never on this screen, for your safety decisions. The token is stored on this machine and sent only to alerts.in.ua.",
     "Цей екран читає активні тривоги з громадського API alerts.in.ua за токеном, який ви отримуєте самі. Дані проходять через сторонню інфраструктуру і надходять із затримкою від секунд до хвилин; застосунок опитує їх кожні пів хвилини. Ставтеся до цього лише як до зручного дисплея - для рішень про безпеку завжди покладайтеся на офіційні сирени й державні канали оповіщення, а не на цей екран. Токен зберігається на цьому комп'ютері й надсилається лише на alerts.in.ua.",
     "此屏幕使用您自行申请的令牌从社区 alerts.in.ua API 读取当前警报。数据经第三方基础设施传递，会有数秒至数分钟的延迟；应用每半分钟轮询一次。请仅将其视为便利显示 - 安全决策请始终依赖官方警报器和政府警报渠道，而非此屏幕。令牌保存在本机，仅发送给 alerts.in.ua。"),





    ("RiskTelegramTitle",   "Telegram login: a note", "Вхід у Telegram: примітка", "Telegram 登录提示"),
        ("RiskTelegramHeading",
     "The session key stays on this machine",
     "Ключ сесії лишається на цьому комп'ютері",
     "会话密钥仅保存在本机"),
        ("RiskTelegramBody",
     "You sign in to your own Telegram account through the official MTProto API (via the open-source WTelegramClient library). The login creates a session key - the most sensitive piece of data this app stores. It is kept in a file on this machine, is sent only to Telegram's servers, and 'Log out' wipes it. api_id, api_hash and your phone number are stored in the settings file as plain text. Message popups are drawn on the keyboard screen only; nothing is forwarded anywhere. If anyone else uses this computer, prefer the count-only privacy mode and log out when done.",
     "Ви входите у власний акаунт Telegram через офіційний MTProto API (бібліотека з відкритим кодом WTelegramClient). Під час входу створюється ключ сесії - найчутливіші дані, які зберігає застосунок. Він лежить у файлі на цьому комп'ютері, надсилається лише на сервери Telegram, а кнопка «Вийти» стирає його. api_id, api_hash і номер телефону зберігаються у файлі налаштувань у відкритому вигляді. Попапи повідомлень малюються лише на екрані клавіатури; нікуди більше нічого не пересилається. Якщо комп'ютером користується ще хтось, обирайте режим «лише кількість» і виходьте після роботи.",
     "您通过官方 MTProto API（开源库 WTelegramClient）登录自己的 Telegram 账号。登录会生成会话密钥 - 这是本应用存储的最敏感数据。它保存在本机文件中，只发送到 Telegram 服务器，点击“退出”即会清除。api_id、api_hash 和手机号以明文保存在设置文件中。消息弹窗只绘制在键盘屏上，不会转发到任何地方。若他人也使用这台电脑，建议选择“仅显示数量”模式并在用完后退出。"),
    ("LoadingGitHub",          "Reading GitHub activity…", "Читаю активність GitHub…", "正在读取 GitHub 活动…"),
    ("RiskGitHubTitle",   "GitHub activity: a note", "Активність GitHub: примітка", "GitHub 活动提示"),
    ("RiskGitHubHeading", "Where the data goes", "Куди йдуть дані", "数据去向"),
        ("RiskGitHubBody",
     "Without a token, KSS fetches the public contribution page for the username you enter, over HTTPS, from github.com. If you add a token, it is kept in this machine's settings file as plain text and sent only to api.github.com - use a fine-grained token with no extra permissions, treat it like a password, and revoke it at any time in your GitHub settings.",
     "Без токена KSS завантажує публічну сторінку контрибуцій для вказаного імені через HTTPS з github.com. Якщо ви додасте токен, він зберігається у файлі налаштувань цього комп'ютера у відкритому вигляді й надсилається лише на api.github.com - використовуйте fine-grained токен без зайвих дозволів, поводьтеся з ним як із паролем і будь-коли відкликайте його в налаштуваннях GitHub.",
     "不提供令牌时，KSS 仅通过 HTTPS 从 github.com 获取所填用户名的公开贡献页面。若添加令牌，它将以明文保存在本机设置文件中，且只发送到 api.github.com — 请使用无额外权限的细粒度令牌，像对待密码一样对待它，并可随时在 GitHub 设置中撤销。"),


    # appended: synced from PR #25
    ("KnobBoundClear",
     "Clear",
     "Очистити",
     "清除"),
    ("KnobBoundLabel",
     "Bound knob",
     "Прив'язана крутілка",
     "已绑定的旋钮"),
    ("KnobBoundNone",
     "Not detected yet - every volume key counts as the knob",
     "Ще не визначено - крутілкою вважається будь-яка клавіша гучності",
     "尚未检测 — 任何音量键都会被当作旋钮"),
    ("KnobDetectCancel",
     "Cancel",
     "Скасувати",
     "取消"),
    ("KnobDetectClose",
     "Close",
     "Закрити",
     "关闭"),
    ("KnobDetectFinish",
     "Finish",
     "Готово",
     "完成"),
    ("KnobDetectHint",
     "Detection learns the HID collection the knob itself speaks on, which is what separates it from the same keyboard's Fn volume keys - a VID:PID cannot, because they share one. It takes precedence over the field above.",
     "Визначення запам'ятовує HID-колекцію, якою говорить сама крутілка - саме це відрізняє її від Fn-клавіш гучності тієї ж клавіатури, бо VID:PID у них спільний. Має пріоритет над полем вище.",
     "检测会记住旋钮本身使用的 HID 集合，这正是它与同一键盘 Fn 音量键的区别所在，因为两者的 VID:PID 相同。其优先级高于上面的字段。"),
    ("KnobDetectNext",
     "Next",
     "Далі",
     "下一步"),
    ("KnobDetectNothing",
     "Nothing heard yet",
     "Поки нічого не почуто",
     "尚未收到任何信号"),
    ("KnobDetectResultBound",
     "Done - the knob is bound to {0}. The other volume keys are left alone.",
     "Готово - крутілку прив'язано до {0}. Інші клавіші гучності не зачіпаються.",
     "完成 — 旋钮已绑定到 {0}。其他音量键不受影响。"),
    ("KnobDetectResultHotKeys",
     "The knob already sends plain keys ({0}), so volume is never involved. Switch the input mode to dedicated keys and pick them there.",
     "Крутілка вже шле звичайні клавіші ({0}), тож гучність не задіяна взагалі. Перемкніть режим на окремі клавіші й виберіть їх там.",
     "旋钮已经发送普通按键（{0}），完全不涉及音量。请将输入模式切换为专用按键并在那里选择它们。"),
    ("KnobDetectResultNothing",
     "No volume report arrived. Check that the knob is turning and that the keyboard is connected.",
     "Жодного звіту про гучність не надійшло. Перевірте, чи крутиться крутілка і чи під'єднана клавіатура.",
     "没有收到音量报告。请确认旋钮在转动且键盘已连接。"),
    ("KnobDetectResultSame",
     "This keyboard sends the knob and the volume keys through one HID collection with the same usages, so nothing can tell them apart. Remap the encoder to F13-F24 in VIA/QMK and switch to dedicated-keys mode.",
     "Ця клавіатура шле крутілку й клавіші гучності однією HID-колекцією з однаковими usage, тож розрізнити їх неможливо. Перепризначте енкодер на F13-F24 у VIA/QMK і перемкніть режим на окремі клавіші.",
     "该键盘通过同一个 HID 集合、以相同的 usage 发送旋钮和音量键，因此无法区分。请在 VIA/QMK 中把编码器重映射为 F13-F24，并切换到专用按键模式。"),
    ("KnobDetectSkip",
     "No such keys",
     "Таких немає",
     "没有这类按键"),
    ("KnobDetectStart",
     "Detect the knob",
     "Визначити крутілку",
     "检测旋钮"),
    ("KnobDetectStep1",
     "Step 1 of 2: turn the knob",
     "Крок 1 з 2: покрутіть крутілку",
     "第 1 步，共 2 步：转动旋钮"),
    ("KnobDetectStep1Hint",
     "Turn it several times in both directions and press it. Volume still works while detecting - nothing is swallowed yet.",
     "Покрутіть кілька разів в обидва боки й натисніть її. Гучність під час визначення працює - нічого ще не перехоплюється.",
     "向两个方向各转动几次并按下它。检测期间音量仍然可用，尚未拦截任何按键。"),
    ("KnobDetectStep2",
     "Step 2 of 2: press the other volume keys",
     "Крок 2 з 2: натисніть інші клавіші гучності",
     "第 2 步，共 2 步：按下其他音量键"),
    ("KnobDetectStep2Hint",
     "Use the keyboard's Fn volume keys - the ones that must keep controlling the volume. Skip if this keyboard has none.",
     "Скористайтеся Fn-клавішами гучності - тими, що мають далі керувати звуком. Пропустіть, якщо таких немає.",
     "请使用键盘的 Fn 音量键，也就是之后仍要控制音量的那些。若没有这类按键，请跳过。"),
    ("KnobHeardKey",
     "key {0}",
     "клавіша {0}",
     "按键 {0}"),
    ("KnobUsageMute",
     "Mute",
     "Без звуку",
     "静音"),
    ("KnobUsageNone",
     "release",
     "відпускання",
     "释放"),
    ("KnobUsageOther",
     "usage {0}",
     "usage {0}",
     "usage {0}"),
    ("KnobUsageVolumeDown",
     "Volume Down",
     "Тихіше",
     "音量-"),
    ("KnobUsageVolumeUp",
     "Volume Up",
     "Гучніше",
     "音量+"),

    # ---- composer editor (v1.7.0) --------------------------------------------
    ("ComposerHeading",         "Screen builder", "Конструктор екрана", "屏幕构建器"),
    ("ComposerHint",            "Stack widgets top to bottom - the preview shows the result live.",
                                "Складайте віджети зверху вниз - прев'ю одразу показує результат.",
                                "自上而下堆叠小组件，预览实时显示效果。"),
    ("ComposerAdd",             "Add", "Додати", "添加"),
    ("ComposerBudget",          "Used {0} of {1} px", "Зайнято {0} із {1} px", "已用 {0}/{1} 像素"),
    ("ComposerBudgetOverflow",  "Widgets past the limit are hidden", "Віджети поза лімітом сховані", "超出上限的小组件将被隐藏"),
    ("ComposerMoveUp",          "Up", "Вгору", "上移"),
    ("ComposerMoveDown",        "Down", "Вниз", "下移"),
    ("ComposerRemove",          "Remove", "Прибрати", "移除"),
    ("ComposerTextPlaceholder", "Your text", "Ваш текст", "自定义文本"),
    ("ComposerWidgetClock",         "Clock", "Годинник", "时钟"),
    ("ComposerWidgetDate",          "Date", "Дата", "日期"),
    ("ComposerWidgetCpu",           "CPU load", "Навантаження CPU", "CPU 负载"),
    ("ComposerWidgetRam",           "Memory", "Пам'ять", "内存"),
    ("ComposerWidgetGpu",           "GPU load", "Навантаження GPU", "GPU 负载"),
    ("ComposerWidgetNet",           "Network speed", "Швидкість мережі", "网络速度"),
    ("ComposerWidgetHardware",      "CPU temp / clock / fan", "Темп./част./вентилятор CPU", "CPU 温度/频率/风扇"),
    ("ComposerWidgetWeather",       "Weather now", "Погода зараз", "当前天气"),
    ("ComposerWidgetCurrency",      "Currency rates", "Курси валют", "汇率"),
    ("ComposerWidgetCrypto",        "Crypto price", "Ціна криптовалюти", "加密货币价格"),
    ("ComposerWidgetPing",          "Ping", "Пінг", "延迟"),
    ("ComposerWidgetAlerts",        "Air alert status", "Статус тривоги", "空袭警报状态"),
    ("ComposerWidgetClaude",        "Claude limits", "Ліміти Claude", "Claude 用量"),
    ("ComposerWidgetPomodoro",      "Pomodoro", "Помодоро", "番茄钟"),
    ("ComposerWidgetMusic",         "Now playing", "Зараз грає", "正在播放"),
    ("ComposerWidgetCalendarNext",  "Next event", "Наступна подія", "下一个日程"),
    ("ComposerWidgetCountdownNext", "Nearest countdown", "Найближчий відлік", "最近的倒计时"),
    ("ComposerWidgetWorldClock",    "World clocks", "Світові годинники", "世界时钟"),
    ("ComposerWidgetGitHub",        "GitHub today", "GitHub сьогодні", "GitHub 今日"),
    ("ComposerWidgetText",          "Custom text", "Довільний текст", "自定义文本"),
    ("ComposerWidgetSpacer",        "Spacer", "Проміжок", "间隔"),
]
