# -*- coding: utf-8 -*-
# (key, en, uk, zh)  -- zh keeps the project's original wording verbatim.
CORE = [
    # ---- date/number formats -------------------------------------------------
    ("FormatLongDate",  "d MMM yyyy", "d MMM yyyy", "yyyy年M月d日"),
    ("FormatShortDate", "d MMM",      "d MMM",      "M月d日"),

    # ---- theme catalogue -----------------------------------------------------
    ("ThemeSystemName",        "PC Status", "Стан ПК", "电脑状态"),
    ("ThemeSystemDescription", "CPU, memory and network", "Процесор, пам'ять і мережа", "CPU、内存与网络状态"),
    ("ThemeSystemDetails",     "Two cards for CPU and memory load, with live download and upload speeds along the bottom.",
                               "Дві картки з навантаженням процесора й пам'яті, а внизу — поточна швидкість завантаження та вивантаження.",
                               "双卡片展示 CPU 和内存占用，并在底部显示实时上下行速度。"),

    ("ThemeDashboardName",        "Status Overview", "Огляд стану", "状态概览"),
    ("ThemeDashboardDescription", "Four system metrics at a glance", "Чотири системні показники разом", "四项系统指标集中展示"),
    ("ThemeDashboardDetails",     "A compact readout of CPU, memory, download and upload speed.",
                                  "Компактно показує процесор, пам'ять, завантаження та вивантаження.",
                                  "紧凑展示 CPU、内存、下载和上传速度。"),

    ("ThemePerformanceName",        "Performance Bars", "Смуги навантаження", "性能条带"),
    ("ThemePerformanceDescription", "Vertical bars with live load", "Вертикальні смуги з поточним навантаженням", "纵向性能条与实时负载"),
    ("ThemePerformanceDetails",     "High-contrast vertical bars for reading CPU and memory pressure at a glance.",
                                    "Контрастні вертикальні смуги, щоб швидко оцінити навантаження процесора й пам'яті.",
                                    "使用高对比度纵向进度条快速查看 CPU 与内存压力。"),

    ("ThemeNetworkName",        "Network Monitor", "Моніторинг мережі", "网络监控"),
    ("ThemeNetworkDescription", "Live download and upload speeds up front", "Поточна швидкість на передньому плані", "突出显示实时上下行速度"),
    ("ThemeNetworkDetails",     "Large figures for download and upload speed, with a CPU and memory summary underneath.",
                                "Великі цифри швидкості завантаження та вивантаження, нижче — зведення по процесору й пам'яті.",
                                "以大号数字展示下载和上传速度，并保留 CPU 与内存摘要。"),

    ("ThemeSystemMinimalName",        "Status Minimal", "Мінімальний стан", "状态极简"),
    ("ThemeSystemMinimalDescription", "Only the essential system figures", "Лише найважливіші системні показники", "仅保留关键系统信息"),
    ("ThemeSystemMinimalDetails",     "A card-free minimal layout for a low-distraction desk.",
                                      "Мінімалістичне компонування без карток — для спокійного робочого столу.",
                                      "无卡片极简排版，适合低干扰桌面。"),

    ("ThemePerformanceVisualName",        "Performance Graphs", "Графіки продуктивності", "性能可视化"),
    ("ThemePerformanceVisualDescription", "CPU, memory, network and GPU usage curves", "Криві процесора, пам'яті, мережі та GPU", "CPU、内存、网络上下行与 GPU 使用率曲线"),
    ("ThemePerformanceVisualDetails",     "Rolling 60-second curves of system performance; GPU reads “N/A” when no data is available.",
                                          "Рухомі криві за останні 60 секунд; якщо дані GPU недоступні, показує «н/д».",
                                          "以最近 60 秒的滚动曲线展示系统性能；GPU 数据不可用时显示为“不可用”。"),

    ("ThemeClockName",        "Minimal Clock", "Мінімальний годинник", "极简时钟"),
    ("ThemeClockDescription", "Time, seconds and the date", "Час, секунди й дата", "时间、秒钟、日期与可定制底部文字"),
    ("ThemeClockDetails",     "Seconds sit on the same baseline as the minutes; the date drops leading zeros.",
                              "Секунди вирівняні по базовій лінії хвилин; дата — без ведучих нулів.",
                              "秒钟与分钟基线对齐；日期使用无前导零的格式。"),

    ("ThemeClockNeonName",        "Neon Clock", "Неоновий годинник", "霓虹时钟"),
    ("ThemeClockNeonDescription", "Large digits in the accent color", "Великі цифри в акцентному кольорі", "强调色大号数字时钟"),
    ("ThemeClockNeonDetails",     "High-contrast neon styling for the time, seconds and date.",
                                  "Контрастний неоновий стиль для часу, секунд і дати.",
                                  "高对比度霓虹风格时间、秒钟和日期。"),

    ("ThemeClockFlipName",        "Flip Clock", "Перекидний годинник", "翻页时钟"),
    ("ThemeClockFlipDescription", "Hours and minutes in separate tiles", "Години й хвилини в окремих плитках", "小时与分钟分栏显示"),
    ("ThemeClockFlipDetails",     "A two-card split-flap layout that also shows seconds and the weekday.",
                                  "Дві картки в стилі перекидного табло; показує також секунди й день тижня.",
                                  "模拟翻页钟的双卡片布局，并显示秒钟与星期。"),

    ("ThemeWeatherFiveDayName",        "Five-Day Weather", "Погода на 5 днів", "五日天气"),
    ("ThemeWeatherFiveDayDescription", "Five-day outlook with highs and lows", "Прогноз на п'ять днів із макс. і мін.", "未来五日天气与高低温"),
    ("ThemeWeatherFiveDayDetails",     "Date, condition and high/low temperature for each of the next five days.",
                                       "Дата, стан погоди та найвища й найнижча температура на кожен із п'яти днів.",
                                       "显示未来五天的日期、天气状态和最高最低温度。"),

    ("ThemeClockDotMatrixName",        "Dot-Matrix Clock", "Точковий годинник", "点阵时钟"),
    ("ThemeClockDotMatrixDescription", "Hours, minutes and seconds stacked in dots", "Години, хвилини й секунди точковою матрицею", "小时、分钟、秒钟纵向点阵显示"),
    ("ThemeClockDotMatrixDetails",     "Three vertical tiers keep hours, minutes and seconds readable on a narrow screen.",
                                       "Три вертикальні рівні тримають години, хвилини й секунди розбірливими на вузькому екрані.",
                                       "使用三段式纵向层级，在小屏上清晰区分小时、分钟与秒钟。"),

    ("ThemeClockWeatherDotName",        "Dot-Matrix Weather Clock", "Точковий годинник із погодою", "点阵时钟天气"),
    ("ThemeClockWeatherDotDescription", "Dot-matrix time with current weather", "Точковий час і поточна погода", "点阵时间与当前天气信息"),
    ("ThemeClockWeatherDotDetails",     "Time, temperature, condition, feels-like and humidity stacked vertically.",
                                        "Час, температура, стан погоди, «відчувається як» і вологість — одне під одним.",
                                        "纵向展示时间、温度、天气状态、体感温度和湿度。"),

    ("ThemeClockDotAnalogName",        "Dot-Matrix Analog Clock", "Точковий стрілковий годинник", "点阵模拟时钟"),
    ("ThemeClockDotAnalogDescription", "A dotted dial over a dense status readout", "Точковий циферблат над щільним зведенням", "点阵指针表盘与高密度状态信息"),
    ("ThemeClockDotAnalogDetails",     "A square dot-matrix dial on top; digital time, date and a PC status summary below.",
                                       "Угорі — квадратний точковий циферблат, унизу — цифровий час, дата й стан комп'ютера.",
                                       "上方使用正方形点阵模拟指针时钟，下方集中显示数字时间、日期和电脑状态摘要。"),

    ("ThemeClockDotProgressName",        "Dot-Matrix Progress", "Точковий прогрес", "点阵进度"),
    ("ThemeClockDotProgressDescription", "Elapsed time as a full-screen dot grid", "Плин часу як повноекранна точкова сітка", "用全屏点阵显示自然时间进度"),
    ("ThemeClockDotProgressDetails",     "Shows how much of the day, week, month, quarter or year has passed; white dots fill from the bottom up.",
                                         "Показує, яка частина дня, тижня, місяця, кварталу чи року минула; білі точки заповнюються знизу вгору.",
                                         "按今天、本周、本月、本季度或本年计算已经经过的比例，白色点阵由下向上逐步填充。"),

    ("ThemeMusicName",        "Music", "Музика", "音乐"),
    ("ThemeMusicDescription", "Artwork, title, artist and progress", "Обкладинка, назва, виконавець і прогрес", "封面、曲名、歌手与播放进度"),
    ("ThemeMusicDetails",     "Reads the Windows media session; live streams show playback state instead of a position.",
                              "Читає медіасесію Windows; для прямих трансляцій показує стан відтворення замість позиції.",
                              "读取 Windows 媒体会话；直播内容自动显示播放状态。"),

    ("ThemeMusicMinimalName",        "Music Minimal", "Музика мінімально", "音乐极简"),
    ("ThemeMusicMinimalDescription", "Text-only music page, no artwork", "Лише текст, без обкладинки", "无封面的纯文字音乐页"),
    ("ThemeMusicMinimalDetails",     "Large title, artist and progress — useful when artwork quality is unreliable.",
                                     "Велика назва, виконавець і прогрес — коли якість обкладинок ненадійна.",
                                     "使用大号曲名、歌手和播放进度，适合封面质量不稳定时。"),

    ("ThemeMusicPosterName",        "Music Poster", "Музичний постер", "音乐海报"),
    ("ThemeMusicPosterDescription", "Full-screen artwork", "Обкладинка на весь екран", "全屏封面音乐页"),
    ("ThemeMusicPosterDetails",     "Full-bleed artwork with title, artist, progress and elapsed/remaining time.",
                                    "Обкладинка на весь екран, назва, виконавець, прогрес і час із обох боків.",
                                    "全屏封面、曲名、歌手、进度与两端时间。"),

        ("ThemeAiQuotaName",
     "AI Usage (Preview)",
     "Витрати AI (прев'ю)",
     "AI用量（开发中）"),
    ("ThemeAiQuotaDescription", "Remaining quota for one platform as an energy bar", "Залишок ліміту однієї платформи у вигляді смуги", "单平台剩余额度能量条"),
    ("ThemeAiQuotaDetails",     "Fills from the bottom up with the remaining AI quota; supports API-key and subscription data.",
                                "Заповнюється знизу вгору залишком ліміту AI; підтримує дані за API-ключем і за підпискою.",
                                "从下向上显示 AI 剩余额度，支持 API Key 与订阅制数据。"),

    ("ThemeStocksName",        "Stocks (Beta)", "Акції (бета)", "股票 (Beta)"),
    ("ThemeStocksDescription", "Two to five quotes with a two-symbol trend chart", "Від двох до п'яти котирувань і порівняння двох", "2-5 项市场行情与双股走势对比"),
    ("ThemeStocksDetails",     "Supports A-share, Hong Kong, US and crypto symbols with custom aliases, gain/loss colors and a choice of data source; with exactly two symbols it draws a five-day trend comparison.",
                               "Підтримує коди A-акцій, Гонконгу, США та криптовалют; налаштовуються псевдоніми, кольори зростання/падіння та джерело даних. Рівно за двома кодами малює порівняння за 5 днів.",
                               "支持 A股、港股、美股与虚拟币代码，可配置别名、涨跌颜色与数据源；恰好两只股票时显示近 5 日走势对比。"),

    ("ThemeImageName",        "Image Clock", "Час на зображенні", "图片时间"),
    ("ThemeImageDescription", "Your picture with time, date and weather on top", "Ваше фото з часом, датою й погодою зверху", "图片背景叠加可定制的时间、日期与天气"),
    ("ThemeImageDetails",     "Digital, large-digital, square analog and flip clock styles, with adjustable position, type size, order and weather.",
                              "Стилі: цифровий, великий цифровий, квадратний стрілковий і перекидний; налаштовуються позиція, кегль, порядок і погода.",
                              "支持数字、大数字、方形模拟与翻页时钟，可调整位置、字号、顺序和天气信息。"),

    ("ThemeClaudeUsageName",        "Claude Usage", "Витрати Claude", "Claude 用量"),
    ("ThemeClaudeUsageDescription", "Session, weekly and per-model limits", "Ліміти сесії, тижня та моделі", "会话、每周与按模型的额度"),
    ("ThemeClaudeUsageDetails",
     "Three meters: the rolling session window, the weekly window across every model, and the weekly window for one model. Percentages come from the account; token counts are summed from the Claude Code transcripts on this machine only.",
     "Три смуги: рухоме вікно сесії, тижневе вікно по всіх моделях і тижневе вікно однієї моделі. Відсотки надходять з акаунта; токени підсумовуються лише з транскриптів Claude Code на цьому комп'ютері.",
     "三条量表：滚动会话窗口、覆盖全部模型的每周窗口，以及单个模型的每周窗口。百分比来自账户；Token 数量仅根据本机的 Claude Code 记录汇总。"),

    ("ThemeCurrencyName",        "Currency Rates", "Курси валют", "汇率"),
    ("ThemeCurrencyDescription", "Daily exchange rates for your currencies", "Щоденні курси обраних валют", "所选货币的每日汇率"),
    ("ThemeCurrencyDetails",     "Up to four quote currencies against a base of your choice, refreshed daily from the open ExchangeRate-API feed.",
                                 "До чотирьох валют відносно обраної базової; дані щодня оновлюються з відкритого фіду ExchangeRate-API.",
                                 "最多四种货币兑所选基准货币，每日从开放的 ExchangeRate-API 源更新。"),

    ("ThemeCryptoName",        "Crypto", "Крипто", "加密货币"),
    ("ThemeCryptoDescription", "Binance prices with 24h sparklines", "Ціни Binance зі спарклайнами за 24 год", "币安价格与 24 小时走势"),
    ("ThemeCryptoDetails",     "Two to four coins from Binance with the live price, 24-hour change and a 24-hour sparkline for each.",
                               "Від двох до чотирьох монет з Binance: поточна ціна, зміна за 24 години та спарклайн за добу для кожної.",
                               "来自币安的 2-4 种币：实时价格、24 小时涨跌幅和 24 小时迷你走势图。"),

    ("ThemePomodoroName",        "Pomodoro", "Помодоро", "番茄钟"),
    ("ThemePomodoroDescription", "Focus timer with cycle tracking", "Таймер фокусу з підрахунком циклів", "带循环统计的专注计时器"),
    ("ThemePomodoroDetails",     "A focus/break timer on the keyboard screen: a countdown ring, the current phase and completed cycles. Start and stop it from settings or the tray menu.",
                                 "Таймер фокусу й перерв на екрані клавіатури: кільце зворотного відліку, поточна фаза та завершені цикли. Запускається з налаштувань або з меню в треї.",
                                 "键盘屏上的专注/休息计时器：倒计时圆环、当前阶段与已完成循环。可在设置或托盘菜单中启动和停止。"),

    ("ThemeHardwareName",        "Hardware Monitor", "Апаратний монітор", "硬件监控"),
    ("ThemeHardwareDescription", "Temps, clocks, fans and VRAM on rotating pages", "Температури, частоти, вентилятори і VRAM на сторінках", "温度、频率、风扇与显存分页轮播"),
    ("ThemeHardwareDetails",     "Two pages that rotate on a configurable dwell: CPU and GPU with temperature, clock and fan speed, then memory, disk and network. Readings the system does not expose show an em dash; CPU temperature usually needs the app to run as administrator.",
                                 "Дві сторінки, що чергуються із заданою затримкою: процесор і відеокарта з температурою, частотою та обертами вентилятора, далі пам'ять, диск і мережа. Недоступні показники позначаються тире; для температури CPU застосунок зазвичай треба запускати від адміністратора.",
                                 "两页按设定间隔轮播：CPU 与 GPU 的温度、频率和风扇转速，然后是内存、磁盘与网络。系统未提供的读数显示为破折号；CPU 温度通常需要以管理员身份运行。"),
    ("ThemeGitHubName",        "GitHub Activity", "Активність GitHub", "GitHub 活动"),
    ("ThemeGitHubDescription", "The contribution graph as a dot matrix", "Графік контрибуцій точковою матрицею", "以点阵显示贡献图"),
        ("ThemeGitHubDetails",
     "The last 17 weeks of the contribution calendar as a dot grid, newest week on top, with this week's and the window's totals. Public data needs only a username; an optional access token also counts private contributions.",
     "Останні 17 тижнів календаря контрибуцій точковою сіткою, найновіший тиждень зверху, із сумами за цей тиждень і за все вікно. Для публічних даних досить імені користувача; необов'язковий токен доступу враховує й приватні контрибуції.",
     "以点阵网格显示最近 17 周的贡献日历，最新一周在顶部，并统计本周与整个窗口的贡献数。公开数据只需用户名；可选的访问令牌还会统计私有贡献。"),
    ("ThemeAlertsName",        "Air Alerts", "Повітряні тривоги", "空袭警报"),
    ("ThemeAlertsDescription", "Air-raid status for your region", "Стан тривоги у вашому регіоні", "所在地区的空袭警报状态"),
    ("ThemeAlertsDetails",     "The alert status for a chosen location - or a whole-country summary - from the alerts.in.ua community API, refreshed every half minute. Informational only, with inherent delays: never rely on it as your only warning source.",
                               "Стан тривоги для обраної локації - або зведення по країні - з громадського API alerts.in.ua, оновлення кожні пів хвилини. Лише інформаційно, із неминучими затримками: ніколи не покладайтеся на це як на єдине джерело оповіщення.",
                               "来自 alerts.in.ua 社区 API 的所选地区警报状态或全国摘要，每半分钟刷新。仅供参考，存在固有延迟：切勿将其作为唯一的警报来源。"),
    ("ThemeCalendarName",        "Calendar", "Календар", "日历"),
    ("ThemeCalendarDescription", "Upcoming events from an ICS feed", "Найближчі події з ICS-стрічки", "来自 ICS 订阅的日程"),
        ("ThemeCalendarDetails",
     "Today's and the upcoming events from a calendar's ICS link (Google, Apple and Outlook all offer one), refreshed every five minutes. Simple repeating events are understood; exotic recurrence rules are shown by their first occurrence only.",
     "Сьогоднішні та найближчі події з ICS-посилання календаря (його дають Google, Apple і Outlook), оновлення кожні п'ять хвилин. Прості повторювані події розгортаються; екзотичні правила повторення показуються лише першою подією.",
     "通过日历的 ICS 链接（Google、Apple、Outlook 均提供）显示今天及未来的日程，每五分钟刷新。支持常见的重复规则；过于复杂的重复规则只显示首次日程。"),
    ("ThemeCountdownName",        "Countdown", "Відлік", "倒计时"),
    ("ThemeCountdownDescription", "Days until your events", "Дні до ваших подій", "距离事件的天数"),
        ("ThemeCountdownDetails",
     "Up to three dates to look forward to: the nearest one large with the days, hours or minutes left, the others in rows below. Dates are set in the theme's settings and live only on this machine.",
     "До трьох дат, на які ви чекаєте: найближча - великим числом днів, годин чи хвилин, решта - рядками нижче. Дати задаються в налаштуваннях теми і зберігаються лише на цьому комп'ютері.",
     "最多三个期待的日期：最近的以大数字显示剩余天数、小时或分钟，其余以行显示。日期在主题设置中填写，仅保存在本机。"),
    ("ThemeWorldClockName",        "World Clock", "Світові годинники", "世界时钟"),
    ("ThemeWorldClockDescription", "Up to four cities side by side", "До чотирьох міст поруч", "最多四个城市并列"),
    ("ThemeWorldClockDetails",     "The local time in up to four places, each with its offset from your clock and a night tint between 22:00 and 07:00. Time zones are entered as IANA names such as Europe/Kyiv or America/New_York.",
                                   "Місцевий час у до чотирьох місцях, кожне зі зсувом відносно вашого годинника і нічним відтінком між 22:00 та 07:00. Часові пояси задаються іменами IANA, як-от Europe/Kyiv чи America/New_York.",
                                   "最多四地的当地时间，均显示与本地时间的差值，22:00-07:00 之间以夜色标注。时区使用 IANA 名称，如 Europe/Kyiv 或 America/New_York。"),
    ("ThemePingName",        "Ping Monitor", "Пінг-монітор", "网络延迟"),
    ("ThemePingDescription", "Latency to your hosts", "Затримка до ваших хостів", "到主机的延迟"),
    ("ThemePingDetails",     "ICMP latency to up to four hosts - the router, a DNS resolver, your server - with a bar history where lost pings stay visible as gaps. Green under 60 ms, orange under 150 ms, red beyond or unreachable.",
                             "ICMP-затримка до чотирьох хостів - роутер, DNS-резолвер, ваш сервер - зі стовпчиковою історією, де втрачені пінги видно як розриви. Зелений до 60 мс, помаранчевий до 150 мс, червоний вище або недосяжно.",
                             "到最多四个主机（路由器、DNS、你的服务器）的 ICMP 延迟，柱状历史中丢包以空缺呈现。60 毫秒内为绿色，150 毫秒内为橙色，更高或不可达为红色。"),
    ("ThemeDisksName",        "Disks", "Диски", "磁盘"),
    ("ThemeDisksDescription", "Fill level of every volume", "Заповненість усіх томів", "所有磁盘的占用"),
    ("ThemeDisksDetails",     "Every ready volume with its used space as a bar - the accent color until 85%, orange to 95%, red beyond. Up to six volumes fit on the screen.",
                              "Кожен готовий том зі смужкою зайнятого місця - акцентний колір до 85%, помаранчевий до 95%, червоний вище. На екран вміщується до шести томів.",
                              "每个就绪磁盘以进度条显示已用空间——85% 以内为主题色，95% 以内为橙色，更高为红色。屏幕最多容纳六个磁盘。"),
]
